import clsx from 'clsx'
import { z } from 'zod'

// Specify icon names to load only the necessary icons, reducing font payload.
// https://developers.google.com/fonts/docs/material_symbols#optimize_the_icon_font
export const IconName = z.enum([
  'add',
  'arrow_back',
  'camera',
  'check',
  'chevron_right',
  'clear',
  'close',
  'delete',
  'description',
  'directions_car',
  'download',
  'error',
  'file_copy',
  'flag',
  'info',
  'keyboard_arrow_down',
  'keyboard_arrow_up',
  'keyboard_arrow_left',
  'keyboard_arrow_right',
  'local_fire_department',
  'logout',
  'menu',
  'my_location',
  'open_in_new',
  'payments',
  'person',
  'progress_activity',
  'satellite_alt',
  'search',
  'settings',
  'upload',
  'videocam',
  'refresh',
  'login',
  'person_off',
  'autorenew',
  'close_small',
  'pause',
  'play_arrow',
  'clear_all',
  'photo_camera',
  'robot_2',
  'bar_chart',
  'home',
  'work',
  'power_settings_new',
  'battery_5_bar',
  'infrared',
  'gamepad',
  'bookmark',
  'bookmark_check',
  'public',
  'public_off',
  'location_on',
  'raw_on',
  'movie',
  'file_json',
  'volume_up',
  'volume_off',
  'mic',
  'mic_off',
  'fullscreen',
  'fullscreen_exit',
  'share',
  'lock',
  'heat',
  'link',
  'content_cut',
  'switches',
  'star',
  'search_off',
  'navigation',
  'joystick',
  'key',
  'route',
  'favorite',
  'explore',
  'alt_route',
  'tune',
  'fingerprint',
  'commit',
  'vpn_key',
  'data_usage',
  'warning',
  'straighten',
  'language',
  'toggle_on',
  'toggle_off',
  'visibility',
  'airline_seat_recline_normal',
  'timer',
  'network_cell',
  'backup',
  'developer_mode',
  'restart_alt',
  'delete_forever',
  'counter_1',
  'schedule',
  'cell_tower',
  'sim_card',
  'verified_user',
  'memory',
  'storage',
  'block',
  'update',
  'wide_angle_camera',
  'pan_tool',
  'remove_red_eye',
  'speed',
  'trending_up',
  'sync',
  'auto_fix_high',
  'model_training',
  'steering',
  'swap_horiz',
  'psychology',
  'timeline',
  'slow_motion_video',
  'turn_slight_right',
  'edit',
  'flash_on',
  'science',
  'brightness_6',
  'brightness_low',
  'signpost',
  'traffic',
  'timer_off',
  'nightlight',
  'traffic_jam',
  'visibility_off',
  'bug_report',
  'departure_board',
  'speedometer',
  'cached',
  'device_hub',
  'gps_fixed',
  'car_crash',
  'cable',
  'build',
  'wifi',
  'thermostat',
  'hardware',
  'usb',
  'priority_high',
  'cloud_off',
  'dns',
  'terminal',
  'cloud_upload',
  'live_tv',
  'smartphone',
  'folder',
  'exit_to_app',
  'bolt',
  'queue',
  'gps_off',
  'hub',
  'security',
  'swap_vert',
  'place',
  'map',
  'cloud_download',
  'calendar_today',
  'update_disabled',
  'group',
  'badge',
  'speed_limit',
  'token',
  'cloud_sync',
  'help',
])

export type IconName = z.infer<typeof IconName>
export const Icons = IconName.options

export type IconProps = {
  className?: string
  name: IconName
  filled?: boolean
  onClick?: () => void
}

/**
 * Use an icon from the Material Symbols library.
 *
 * Note: Icon names <strong>must</strong> be added to the icons list in vite.config.ts.
 *
 * @see https://fonts.google.com/icons
 */
export const Icon = (props: IconProps) => {
  // size-20, 24 etc. defined in root.css
  return (
    <span
      className={clsx(
        'material-symbols-outlined flex select-none',
        props.filled ? 'icon-filled' : 'icon-outline',

        props.className,
      )}
    >
      {props.name}
    </span>
  )
}
