/* tslint:disable */

/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */

import * as capnp from 'capnp-ts'
import { ObjectSize as __O, Struct as __S } from 'capnp-ts'
export const _capnpFileId = '8e2af1e708af8b8d'
export enum OnroadEventDEPRECATED_EventName {
  CAN_ERROR,
  STEER_UNAVAILABLE,
  WRONG_GEAR,
  DOOR_OPEN,
  SEATBELT_NOT_LATCHED,
  ESP_DISABLED,
  WRONG_CAR_MODE,
  STEER_TEMP_UNAVAILABLE,
  REVERSE_GEAR,
  BUTTON_CANCEL,
  BUTTON_ENABLE,
  PEDAL_PRESSED,
  PRE_ENABLE_STANDSTILL,
  GAS_PRESSED_OVERRIDE,
  STEER_OVERRIDE,
  CRUISE_DISABLED,
  SPEED_TOO_LOW,
  OUT_OF_SPACE,
  OVERHEAT,
  CALIBRATION_INCOMPLETE,
  CALIBRATION_INVALID,
  CALIBRATION_RECALIBRATING,
  CONTROLS_MISMATCH,
  PCM_ENABLE,
  PCM_DISABLE,
  RADAR_FAULT,
  BRAKE_HOLD,
  PARK_BRAKE,
  MANUAL_RESTART,
  JOYSTICK_DEBUG,
  LONGITUDINAL_MANEUVER,
  STEER_TEMP_UNAVAILABLE_SILENT,
  RESUME_REQUIRED,
  PRE_DRIVER_DISTRACTED,
  PROMPT_DRIVER_DISTRACTED,
  DRIVER_DISTRACTED,
  PRE_DRIVER_UNRESPONSIVE,
  PROMPT_DRIVER_UNRESPONSIVE,
  DRIVER_UNRESPONSIVE,
  BELOW_STEER_SPEED,
  LOW_BATTERY,
  ACC_FAULTED,
  SENSOR_DATA_INVALID,
  COMM_ISSUE,
  COMM_ISSUE_AVG_FREQ,
  TOO_DISTRACTED,
  POSENET_INVALID,
  PRE_LANE_CHANGE_LEFT,
  PRE_LANE_CHANGE_RIGHT,
  LANE_CHANGE,
  LOW_MEMORY,
  STOCK_AEB,
  LDW,
  CAR_UNRECOGNIZED,
  INVALID_LKAS_SETTING,
  SPEED_TOO_HIGH,
  LANE_CHANGE_BLOCKED,
  RELAY_MALFUNCTION,
  STOCK_FCW,
  STARTUP,
  STARTUP_NO_CAR,
  STARTUP_NO_CONTROL,
  STARTUP_NO_SEC_OC_KEY,
  STARTUP_MASTER,
  FCW,
  STEER_SATURATED,
  BELOW_ENGAGE_SPEED,
  NO_GPS,
  WRONG_CRUISE_MODE,
  MODELD_LAGGING,
  DEVICE_FALLING,
  FAN_MALFUNCTION,
  CAMERA_MALFUNCTION,
  CAMERA_FRAME_RATE,
  PROCESS_NOT_RUNNING,
  DASHCAM_MODE,
  SELFDRIVE_INITIALIZING,
  USB_ERROR,
  CRUISE_MISMATCH,
  CAN_BUS_MISSING,
  SELFDRIVED_LAGGING,
  RESUME_BLOCKED,
  STEER_TIME_LIMIT,
  VEHICLE_SENSORS_INVALID,
  LOCATIOND_TEMPORARY_ERROR,
  LOCATIOND_PERMANENT_ERROR,
  PARAMSD_TEMPORARY_ERROR,
  PARAMSD_PERMANENT_ERROR,
  ACTUATORS_API_UNAVAILABLE,
  ESP_ACTIVE,
  PERSONALITY_CHANGED,
  AEB,
  RADAR_CAN_ERROR_DEPRECATED,
  COMMUNITY_FEATURE_DISALLOWED_DEPRECATED,
  RADAR_COMM_ISSUE_DEPRECATED,
  DRIVER_MONITOR_LOW_ACC_DEPRECATED,
  GAS_UNAVAILABLE_DEPRECATED,
  DATA_NEEDED_DEPRECATED,
  MODEL_COMM_ISSUE_DEPRECATED,
  IPAS_OVERRIDE_DEPRECATED,
  GEOFENCE_DEPRECATED,
  DRIVER_MONITOR_ON_DEPRECATED,
  DRIVER_MONITOR_OFF_DEPRECATED,
  CALIBRATION_PROGRESS_DEPRECATED,
  INVALID_GIRAFFE_HONDA_DEPRECATED,
  INVALID_GIRAFFE_TOYOTA_DEPRECATED,
  INTERNET_CONNECTIVITY_NEEDED_DEPRECATED,
  WHITE_PANDA_UNSUPPORTED_DEPRECATED,
  COMM_ISSUE_WARNING_DEPRECATED,
  FOCUS_RECOVER_ACTIVE_DEPRECATED,
  NEOS_UPDATE_REQUIRED_DEPRECATED,
  MODEL_LAG_WARNING_DEPRECATED,
  STARTUP_ONEPLUS_DEPRECATED,
  STARTUP_FUZZY_FINGERPRINT_DEPRECATED,
  NO_TARGET_DEPRECATED,
  BRAKE_UNAVAILABLE_DEPRECATED,
  PLANNER_ERROR_DEPRECATED,
  GPS_MALFUNCTION_DEPRECATED,
  ROAD_CAMERA_ERROR_DEPRECATED,
  DRIVER_CAMERA_ERROR_DEPRECATED,
  WIDE_ROAD_CAMERA_ERROR_DEPRECATED,
  HIGH_CPU_USAGE_DEPRECATED,
  STARTUP_NO_FW_DEPRECATED,
  LOW_SPEED_LOCKOUT_DEPRECATED,
  LKAS_DISABLED_DEPRECATED,
  SOUNDS_UNAVAILABLE_DEPRECATED,
}
export class OnroadEventDEPRECATED extends __S {
  static readonly EventName = OnroadEventDEPRECATED_EventName
  static readonly _capnp = { displayName: 'OnroadEventDEPRECATED', id: '9b1657f34caf3ad3', size: new __O(8, 0) }
  getName(): OnroadEventDEPRECATED_EventName {
    return __S.getUint16(0, this)
  }
  setName(value: OnroadEventDEPRECATED_EventName): void {
    __S.setUint16(0, value, this)
  }
  getEnable(): boolean {
    return __S.getBit(16, this)
  }
  setEnable(value: boolean): void {
    __S.setBit(16, value, this)
  }
  getNoEntry(): boolean {
    return __S.getBit(17, this)
  }
  setNoEntry(value: boolean): void {
    __S.setBit(17, value, this)
  }
  getWarning(): boolean {
    return __S.getBit(18, this)
  }
  setWarning(value: boolean): void {
    __S.setBit(18, value, this)
  }
  getUserDisable(): boolean {
    return __S.getBit(19, this)
  }
  setUserDisable(value: boolean): void {
    __S.setBit(19, value, this)
  }
  getSoftDisable(): boolean {
    return __S.getBit(20, this)
  }
  setSoftDisable(value: boolean): void {
    __S.setBit(20, value, this)
  }
  getImmediateDisable(): boolean {
    return __S.getBit(21, this)
  }
  setImmediateDisable(value: boolean): void {
    __S.setBit(21, value, this)
  }
  getPreEnable(): boolean {
    return __S.getBit(22, this)
  }
  setPreEnable(value: boolean): void {
    __S.setBit(22, value, this)
  }
  getPermanent(): boolean {
    return __S.getBit(23, this)
  }
  setPermanent(value: boolean): void {
    __S.setBit(23, value, this)
  }
  getOverrideLateral(): boolean {
    return __S.getBit(25, this)
  }
  setOverrideLateral(value: boolean): void {
    __S.setBit(25, value, this)
  }
  getOverrideLongitudinal(): boolean {
    return __S.getBit(24, this)
  }
  setOverrideLongitudinal(value: boolean): void {
    __S.setBit(24, value, this)
  }
  toString(): string {
    return 'OnroadEventDEPRECATED_' + super.toString()
  }
}
export class CarState_WheelSpeeds extends __S {
  static readonly _capnp = { displayName: 'WheelSpeeds', id: '991a37a6155935a3', size: new __O(16, 0) }
  getFl(): number {
    return __S.getFloat32(0, this)
  }
  setFl(value: number): void {
    __S.setFloat32(0, value, this)
  }
  getFr(): number {
    return __S.getFloat32(4, this)
  }
  setFr(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getRl(): number {
    return __S.getFloat32(8, this)
  }
  setRl(value: number): void {
    __S.setFloat32(8, value, this)
  }
  getRr(): number {
    return __S.getFloat32(12, this)
  }
  setRr(value: number): void {
    __S.setFloat32(12, value, this)
  }
  toString(): string {
    return 'CarState_WheelSpeeds_' + super.toString()
  }
}
export class CarState_CruiseState extends __S {
  static readonly _capnp = { displayName: 'CruiseState', id: 'e64e81478e6e60af', size: new __O(16, 0) }
  getEnabled(): boolean {
    return __S.getBit(0, this)
  }
  setEnabled(value: boolean): void {
    __S.setBit(0, value, this)
  }
  getSpeed(): number {
    return __S.getFloat32(4, this)
  }
  setSpeed(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getSpeedCluster(): number {
    return __S.getFloat32(12, this)
  }
  setSpeedCluster(value: number): void {
    __S.setFloat32(12, value, this)
  }
  getAvailable(): boolean {
    return __S.getBit(1, this)
  }
  setAvailable(value: boolean): void {
    __S.setBit(1, value, this)
  }
  getStandstill(): boolean {
    return __S.getBit(2, this)
  }
  setStandstill(value: boolean): void {
    __S.setBit(2, value, this)
  }
  getNonAdaptive(): boolean {
    return __S.getBit(3, this)
  }
  setNonAdaptive(value: boolean): void {
    __S.setBit(3, value, this)
  }
  getSpeedOffsetDEPRECATED(): number {
    return __S.getFloat32(8, this)
  }
  setSpeedOffsetDEPRECATED(value: number): void {
    __S.setFloat32(8, value, this)
  }
  toString(): string {
    return 'CarState_CruiseState_' + super.toString()
  }
}
export enum CarState_GearShifter {
  UNKNOWN,
  PARK,
  DRIVE,
  NEUTRAL,
  REVERSE,
  SPORT,
  LOW,
  BRAKE,
  ECO,
  MANUMATIC,
}
export enum CarState_ButtonEvent_Type {
  UNKNOWN,
  LEFT_BLINKER,
  RIGHT_BLINKER,
  ACCEL_CRUISE,
  DECEL_CRUISE,
  CANCEL,
  LKAS,
  ALT_BUTTON2,
  MAIN_CRUISE,
  SET_CRUISE,
  RESUME_CRUISE,
  GAP_ADJUST_CRUISE,
}
export class CarState_ButtonEvent extends __S {
  static readonly Type = CarState_ButtonEvent_Type
  static readonly _capnp = { displayName: 'ButtonEvent', id: 'ff5ca6835b4acef6', size: new __O(8, 0) }
  getPressed(): boolean {
    return __S.getBit(0, this)
  }
  setPressed(value: boolean): void {
    __S.setBit(0, value, this)
  }
  getType(): CarState_ButtonEvent_Type {
    return __S.getUint16(2, this)
  }
  setType(value: CarState_ButtonEvent_Type): void {
    __S.setUint16(2, value, this)
  }
  toString(): string {
    return 'CarState_ButtonEvent_' + super.toString()
  }
}
export class CarState extends __S {
  static readonly WheelSpeeds = CarState_WheelSpeeds
  static readonly CruiseState = CarState_CruiseState
  static readonly GearShifter = CarState_GearShifter
  static readonly ButtonEvent = CarState_ButtonEvent
  static readonly _capnp = { displayName: 'CarState', id: '9da4fa09e052903c', size: new __O(80, 6) }
  static _ButtonEvents: capnp.ListCtor<CarState_ButtonEvent>
  static _EventsDEPRECATED: capnp.ListCtor<OnroadEventDEPRECATED>
  getCanValid(): boolean {
    return __S.getBit(74, this)
  }
  setCanValid(value: boolean): void {
    __S.setBit(74, value, this)
  }
  getCanTimeout(): boolean {
    return __S.getBit(358, this)
  }
  setCanTimeout(value: boolean): void {
    __S.setBit(358, value, this)
  }
  getCanErrorCounter(): number {
    return __S.getUint32(64, this)
  }
  setCanErrorCounter(value: number): void {
    __S.setUint32(64, value, this)
  }
  getCumLagMs(): number {
    return __S.getFloat32(68, this)
  }
  setCumLagMs(value: number): void {
    __S.setFloat32(68, value, this)
  }
  getVEgo(): number {
    return __S.getFloat32(0, this)
  }
  setVEgo(value: number): void {
    __S.setFloat32(0, value, this)
  }
  getAEgo(): number {
    return __S.getFloat32(28, this)
  }
  setAEgo(value: number): void {
    __S.setFloat32(28, value, this)
  }
  getVEgoRaw(): number {
    return __S.getFloat32(32, this)
  }
  setVEgoRaw(value: number): void {
    __S.setFloat32(32, value, this)
  }
  getVEgoCluster(): number {
    return __S.getFloat32(56, this)
  }
  setVEgoCluster(value: number): void {
    __S.setFloat32(56, value, this)
  }
  getVCruise(): number {
    return __S.getFloat32(72, this)
  }
  setVCruise(value: number): void {
    __S.setFloat32(72, value, this)
  }
  getVCruiseCluster(): number {
    return __S.getFloat32(76, this)
  }
  setVCruiseCluster(value: number): void {
    __S.setFloat32(76, value, this)
  }
  getYawRate(): number {
    return __S.getFloat32(36, this)
  }
  setYawRate(value: number): void {
    __S.setFloat32(36, value, this)
  }
  getStandstill(): boolean {
    return __S.getBit(67, this)
  }
  setStandstill(value: boolean): void {
    __S.setBit(67, value, this)
  }
  adoptWheelSpeeds(value: capnp.Orphan<CarState_WheelSpeeds>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownWheelSpeeds(): capnp.Orphan<CarState_WheelSpeeds> {
    return __S.disown(this.getWheelSpeeds())
  }
  getWheelSpeeds(): CarState_WheelSpeeds {
    return __S.getStruct(1, CarState_WheelSpeeds, this)
  }
  hasWheelSpeeds(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initWheelSpeeds(): CarState_WheelSpeeds {
    return __S.initStructAt(1, CarState_WheelSpeeds, this)
  }
  setWheelSpeeds(value: CarState_WheelSpeeds): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  getGasPressed(): boolean {
    return __S.getBit(64, this)
  }
  setGasPressed(value: boolean): void {
    __S.setBit(64, value, this)
  }
  getBrake(): number {
    return __S.getFloat32(12, this)
  }
  setBrake(value: number): void {
    __S.setFloat32(12, value, this)
  }
  getBrakePressed(): boolean {
    return __S.getBit(65, this)
  }
  setBrakePressed(value: boolean): void {
    __S.setBit(65, value, this)
  }
  getRegenBraking(): boolean {
    return __S.getBit(361, this)
  }
  setRegenBraking(value: boolean): void {
    __S.setBit(361, value, this)
  }
  getParkingBrake(): boolean {
    return __S.getBit(357, this)
  }
  setParkingBrake(value: boolean): void {
    __S.setBit(357, value, this)
  }
  getBrakeHoldActive(): boolean {
    return __S.getBit(356, this)
  }
  setBrakeHoldActive(value: boolean): void {
    __S.setBit(356, value, this)
  }
  getSteeringAngleDeg(): number {
    return __S.getFloat32(16, this)
  }
  setSteeringAngleDeg(value: number): void {
    __S.setFloat32(16, value, this)
  }
  getSteeringAngleOffsetDeg(): number {
    return __S.getFloat32(48, this)
  }
  setSteeringAngleOffsetDeg(value: number): void {
    __S.setFloat32(48, value, this)
  }
  getSteeringRateDeg(): number {
    return __S.getFloat32(24, this)
  }
  setSteeringRateDeg(value: number): void {
    __S.setFloat32(24, value, this)
  }
  getSteeringTorque(): number {
    return __S.getFloat32(20, this)
  }
  setSteeringTorque(value: number): void {
    __S.setFloat32(20, value, this)
  }
  getSteeringTorqueEps(): number {
    return __S.getFloat32(40, this)
  }
  setSteeringTorqueEps(value: number): void {
    __S.setFloat32(40, value, this)
  }
  getSteeringPressed(): boolean {
    return __S.getBit(66, this)
  }
  setSteeringPressed(value: boolean): void {
    __S.setBit(66, value, this)
  }
  getSteeringDisengage(): boolean {
    return __S.getBit(369, this)
  }
  setSteeringDisengage(value: boolean): void {
    __S.setBit(369, value, this)
  }
  getSteerFaultTemporary(): boolean {
    return __S.getBit(354, this)
  }
  setSteerFaultTemporary(value: boolean): void {
    __S.setBit(354, value, this)
  }
  getSteerFaultPermanent(): boolean {
    return __S.getBit(355, this)
  }
  setSteerFaultPermanent(value: boolean): void {
    __S.setBit(355, value, this)
  }
  getInvalidLkasSetting(): boolean {
    return __S.getBit(366, this)
  }
  setInvalidLkasSetting(value: boolean): void {
    __S.setBit(366, value, this)
  }
  getStockAeb(): boolean {
    return __S.getBit(77, this)
  }
  setStockAeb(value: boolean): void {
    __S.setBit(77, value, this)
  }
  getStockLkas(): boolean {
    return __S.getBit(370, this)
  }
  setStockLkas(value: boolean): void {
    __S.setBit(370, value, this)
  }
  getStockFcw(): boolean {
    return __S.getBit(78, this)
  }
  setStockFcw(value: boolean): void {
    __S.setBit(78, value, this)
  }
  getEspDisabled(): boolean {
    return __S.getBit(79, this)
  }
  setEspDisabled(value: boolean): void {
    __S.setBit(79, value, this)
  }
  getAccFaulted(): boolean {
    return __S.getBit(359, this)
  }
  setAccFaulted(value: boolean): void {
    __S.setBit(359, value, this)
  }
  getCarFaultedNonCritical(): boolean {
    return __S.getBit(362, this)
  }
  setCarFaultedNonCritical(value: boolean): void {
    __S.setBit(362, value, this)
  }
  getEspActive(): boolean {
    return __S.getBit(364, this)
  }
  setEspActive(value: boolean): void {
    __S.setBit(364, value, this)
  }
  getVehicleSensorsInvalid(): boolean {
    return __S.getBit(365, this)
  }
  setVehicleSensorsInvalid(value: boolean): void {
    __S.setBit(365, value, this)
  }
  getLowSpeedAlert(): boolean {
    return __S.getBit(367, this)
  }
  setLowSpeedAlert(value: boolean): void {
    __S.setBit(367, value, this)
  }
  getBlockPcmEnable(): boolean {
    return __S.getBit(371, this)
  }
  setBlockPcmEnable(value: boolean): void {
    __S.setBit(371, value, this)
  }
  adoptCruiseState(value: capnp.Orphan<CarState_CruiseState>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownCruiseState(): capnp.Orphan<CarState_CruiseState> {
    return __S.disown(this.getCruiseState())
  }
  getCruiseState(): CarState_CruiseState {
    return __S.getStruct(2, CarState_CruiseState, this)
  }
  hasCruiseState(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initCruiseState(): CarState_CruiseState {
    return __S.initStructAt(2, CarState_CruiseState, this)
  }
  setCruiseState(value: CarState_CruiseState): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  getGearShifter(): CarState_GearShifter {
    return __S.getUint16(10, this)
  }
  setGearShifter(value: CarState_GearShifter): void {
    __S.setUint16(10, value, this)
  }
  adoptButtonEvents(value: capnp.Orphan<capnp.List<CarState_ButtonEvent>>): void {
    __S.adopt(value, __S.getPointer(3, this))
  }
  disownButtonEvents(): capnp.Orphan<capnp.List<CarState_ButtonEvent>> {
    return __S.disown(this.getButtonEvents())
  }
  getButtonEvents(): capnp.List<CarState_ButtonEvent> {
    return __S.getList(3, CarState._ButtonEvents, this)
  }
  hasButtonEvents(): boolean {
    return !__S.isNull(__S.getPointer(3, this))
  }
  initButtonEvents(length: number): capnp.List<CarState_ButtonEvent> {
    return __S.initList(3, CarState._ButtonEvents, length, this)
  }
  setButtonEvents(value: capnp.List<CarState_ButtonEvent>): void {
    __S.copyFrom(value, __S.getPointer(3, this))
  }
  getButtonEnable(): boolean {
    return __S.getBit(368, this)
  }
  setButtonEnable(value: boolean): void {
    __S.setBit(368, value, this)
  }
  getLeftBlinker(): boolean {
    return __S.getBit(69, this)
  }
  setLeftBlinker(value: boolean): void {
    __S.setBit(69, value, this)
  }
  getRightBlinker(): boolean {
    return __S.getBit(70, this)
  }
  setRightBlinker(value: boolean): void {
    __S.setBit(70, value, this)
  }
  getGenericToggle(): boolean {
    return __S.getBit(71, this)
  }
  setGenericToggle(value: boolean): void {
    __S.setBit(71, value, this)
  }
  getDoorOpen(): boolean {
    return __S.getBit(72, this)
  }
  setDoorOpen(value: boolean): void {
    __S.setBit(72, value, this)
  }
  getSeatbeltUnlatched(): boolean {
    return __S.getBit(73, this)
  }
  setSeatbeltUnlatched(value: boolean): void {
    __S.setBit(73, value, this)
  }
  getLeftBlindspot(): boolean {
    return __S.getBit(352, this)
  }
  setLeftBlindspot(value: boolean): void {
    __S.setBit(352, value, this)
  }
  getRightBlindspot(): boolean {
    return __S.getBit(353, this)
  }
  setRightBlindspot(value: boolean): void {
    __S.setBit(353, value, this)
  }
  getFuelGauge(): number {
    return __S.getFloat32(52, this)
  }
  setFuelGauge(value: number): void {
    __S.setFloat32(52, value, this)
  }
  getCharging(): boolean {
    return __S.getBit(360, this)
  }
  setCharging(value: boolean): void {
    __S.setBit(360, value, this)
  }
  adoptErrorsDEPRECATED(value: capnp.Orphan<capnp.List<OnroadEventDEPRECATED_EventName>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownErrorsDEPRECATED(): capnp.Orphan<capnp.List<OnroadEventDEPRECATED_EventName>> {
    return __S.disown(this.getErrorsDEPRECATED())
  }
  getErrorsDEPRECATED(): capnp.List<OnroadEventDEPRECATED_EventName> {
    return __S.getList(0, capnp.Uint16List, this)
  }
  hasErrorsDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initErrorsDEPRECATED(length: number): capnp.List<OnroadEventDEPRECATED_EventName> {
    return __S.initList(0, capnp.Uint16List, length, this)
  }
  setErrorsDEPRECATED(value: capnp.List<OnroadEventDEPRECATED_EventName>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  getGasDEPRECATED(): number {
    return __S.getFloat32(4, this)
  }
  setGasDEPRECATED(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getBrakeLightsDEPRECATED(): boolean {
    return __S.getBit(68, this)
  }
  setBrakeLightsDEPRECATED(value: boolean): void {
    __S.setBit(68, value, this)
  }
  getSteeringRateLimitedDEPRECATED(): boolean {
    return __S.getBit(76, this)
  }
  setSteeringRateLimitedDEPRECATED(value: boolean): void {
    __S.setBit(76, value, this)
  }
  adoptCanMonoTimesDEPRECATED(value: capnp.Orphan<capnp.List<capnp.Uint64>>): void {
    __S.adopt(value, __S.getPointer(4, this))
  }
  disownCanMonoTimesDEPRECATED(): capnp.Orphan<capnp.List<capnp.Uint64>> {
    return __S.disown(this.getCanMonoTimesDEPRECATED())
  }
  getCanMonoTimesDEPRECATED(): capnp.List<capnp.Uint64> {
    return __S.getList(4, capnp.Uint64List, this)
  }
  hasCanMonoTimesDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(4, this))
  }
  initCanMonoTimesDEPRECATED(length: number): capnp.List<capnp.Uint64> {
    return __S.initList(4, capnp.Uint64List, length, this)
  }
  setCanMonoTimesDEPRECATED(value: capnp.List<capnp.Uint64>): void {
    __S.copyFrom(value, __S.getPointer(4, this))
  }
  getCanRcvTimeoutDEPRECATED(): boolean {
    return __S.getBit(363, this)
  }
  setCanRcvTimeoutDEPRECATED(value: boolean): void {
    __S.setBit(363, value, this)
  }
  adoptEventsDEPRECATED(value: capnp.Orphan<capnp.List<OnroadEventDEPRECATED>>): void {
    __S.adopt(value, __S.getPointer(5, this))
  }
  disownEventsDEPRECATED(): capnp.Orphan<capnp.List<OnroadEventDEPRECATED>> {
    return __S.disown(this.getEventsDEPRECATED())
  }
  getEventsDEPRECATED(): capnp.List<OnroadEventDEPRECATED> {
    return __S.getList(5, CarState._EventsDEPRECATED, this)
  }
  hasEventsDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(5, this))
  }
  initEventsDEPRECATED(length: number): capnp.List<OnroadEventDEPRECATED> {
    return __S.initList(5, CarState._EventsDEPRECATED, length, this)
  }
  setEventsDEPRECATED(value: capnp.List<OnroadEventDEPRECATED>): void {
    __S.copyFrom(value, __S.getPointer(5, this))
  }
  getClutchPressedDEPRECATED(): boolean {
    return __S.getBit(75, this)
  }
  setClutchPressedDEPRECATED(value: boolean): void {
    __S.setBit(75, value, this)
  }
  getEngineRpmDEPRECATED(): number {
    return __S.getFloat32(60, this)
  }
  setEngineRpmDEPRECATED(value: number): void {
    __S.setFloat32(60, value, this)
  }
  toString(): string {
    return 'CarState_' + super.toString()
  }
}
export class RadarData_Error extends __S {
  static readonly _capnp = { displayName: 'Error', id: 'e8a86679ebba76ad', size: new __O(8, 0) }
  getCanError(): boolean {
    return __S.getBit(0, this)
  }
  setCanError(value: boolean): void {
    __S.setBit(0, value, this)
  }
  getRadarFault(): boolean {
    return __S.getBit(1, this)
  }
  setRadarFault(value: boolean): void {
    __S.setBit(1, value, this)
  }
  getWrongConfig(): boolean {
    return __S.getBit(2, this)
  }
  setWrongConfig(value: boolean): void {
    __S.setBit(2, value, this)
  }
  getRadarUnavailableTemporary(): boolean {
    return __S.getBit(3, this)
  }
  setRadarUnavailableTemporary(value: boolean): void {
    __S.setBit(3, value, this)
  }
  toString(): string {
    return 'RadarData_Error_' + super.toString()
  }
}
export class RadarData_RadarPoint extends __S {
  static readonly _capnp = { displayName: 'RadarPoint', id: '8ff333ebac1fdf36', size: new __O(32, 0) }
  getTrackId(): capnp.Uint64 {
    return __S.getUint64(0, this)
  }
  setTrackId(value: capnp.Uint64): void {
    __S.setUint64(0, value, this)
  }
  getDRel(): number {
    return __S.getFloat32(8, this)
  }
  setDRel(value: number): void {
    __S.setFloat32(8, value, this)
  }
  getYRel(): number {
    return __S.getFloat32(12, this)
  }
  setYRel(value: number): void {
    __S.setFloat32(12, value, this)
  }
  getVRel(): number {
    return __S.getFloat32(16, this)
  }
  setVRel(value: number): void {
    __S.setFloat32(16, value, this)
  }
  getARel(): number {
    return __S.getFloat32(20, this)
  }
  setARel(value: number): void {
    __S.setFloat32(20, value, this)
  }
  getYvRel(): number {
    return __S.getFloat32(24, this)
  }
  setYvRel(value: number): void {
    __S.setFloat32(24, value, this)
  }
  getMeasured(): boolean {
    return __S.getBit(224, this)
  }
  setMeasured(value: boolean): void {
    __S.setBit(224, value, this)
  }
  toString(): string {
    return 'RadarData_RadarPoint_' + super.toString()
  }
}
export enum RadarData_ErrorDEPRECATED {
  CAN_ERROR,
  FAULT,
  WRONG_CONFIG,
}
export class RadarData extends __S {
  static readonly Error = RadarData_Error
  static readonly RadarPoint = RadarData_RadarPoint
  static readonly ErrorDEPRECATED = RadarData_ErrorDEPRECATED
  static readonly _capnp = { displayName: 'RadarData', id: '888ad6581cf0aacb', size: new __O(0, 4) }
  static _Points: capnp.ListCtor<RadarData_RadarPoint>
  adoptErrors(value: capnp.Orphan<RadarData_Error>): void {
    __S.adopt(value, __S.getPointer(3, this))
  }
  disownErrors(): capnp.Orphan<RadarData_Error> {
    return __S.disown(this.getErrors())
  }
  getErrors(): RadarData_Error {
    return __S.getStruct(3, RadarData_Error, this)
  }
  hasErrors(): boolean {
    return !__S.isNull(__S.getPointer(3, this))
  }
  initErrors(): RadarData_Error {
    return __S.initStructAt(3, RadarData_Error, this)
  }
  setErrors(value: RadarData_Error): void {
    __S.copyFrom(value, __S.getPointer(3, this))
  }
  adoptPoints(value: capnp.Orphan<capnp.List<RadarData_RadarPoint>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownPoints(): capnp.Orphan<capnp.List<RadarData_RadarPoint>> {
    return __S.disown(this.getPoints())
  }
  getPoints(): capnp.List<RadarData_RadarPoint> {
    return __S.getList(1, RadarData._Points, this)
  }
  hasPoints(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initPoints(length: number): capnp.List<RadarData_RadarPoint> {
    return __S.initList(1, RadarData._Points, length, this)
  }
  setPoints(value: capnp.List<RadarData_RadarPoint>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  adoptCanMonoTimesDEPRECATED(value: capnp.Orphan<capnp.List<capnp.Uint64>>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownCanMonoTimesDEPRECATED(): capnp.Orphan<capnp.List<capnp.Uint64>> {
    return __S.disown(this.getCanMonoTimesDEPRECATED())
  }
  getCanMonoTimesDEPRECATED(): capnp.List<capnp.Uint64> {
    return __S.getList(2, capnp.Uint64List, this)
  }
  hasCanMonoTimesDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initCanMonoTimesDEPRECATED(length: number): capnp.List<capnp.Uint64> {
    return __S.initList(2, capnp.Uint64List, length, this)
  }
  setCanMonoTimesDEPRECATED(value: capnp.List<capnp.Uint64>): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  adoptErrorsDEPRECATED(value: capnp.Orphan<capnp.List<RadarData_ErrorDEPRECATED>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownErrorsDEPRECATED(): capnp.Orphan<capnp.List<RadarData_ErrorDEPRECATED>> {
    return __S.disown(this.getErrorsDEPRECATED())
  }
  getErrorsDEPRECATED(): capnp.List<RadarData_ErrorDEPRECATED> {
    return __S.getList(0, capnp.Uint16List, this)
  }
  hasErrorsDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initErrorsDEPRECATED(length: number): capnp.List<RadarData_ErrorDEPRECATED> {
    return __S.initList(0, capnp.Uint16List, length, this)
  }
  setErrorsDEPRECATED(value: capnp.List<RadarData_ErrorDEPRECATED>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  toString(): string {
    return 'RadarData_' + super.toString()
  }
}
export enum CarControl_Actuators_LongControlState {
  OFF,
  PID,
  STOPPING,
  STARTING,
}
export class CarControl_Actuators extends __S {
  static readonly LongControlState = CarControl_Actuators_LongControlState
  static readonly _capnp = { displayName: 'Actuators', id: 'e97275a919432828', size: new __O(40, 0) }
  getTorque(): number {
    return __S.getFloat32(8, this)
  }
  setTorque(value: number): void {
    __S.setFloat32(8, value, this)
  }
  getSteeringAngleDeg(): number {
    return __S.getFloat32(12, this)
  }
  setSteeringAngleDeg(value: number): void {
    __S.setFloat32(12, value, this)
  }
  getCurvature(): number {
    return __S.getFloat32(28, this)
  }
  setCurvature(value: number): void {
    __S.setFloat32(28, value, this)
  }
  getAccel(): number {
    return __S.getFloat32(16, this)
  }
  setAccel(value: number): void {
    __S.setFloat32(16, value, this)
  }
  getLongControlState(): CarControl_Actuators_LongControlState {
    return __S.getUint16(20, this)
  }
  setLongControlState(value: CarControl_Actuators_LongControlState): void {
    __S.setUint16(20, value, this)
  }
  getGas(): number {
    return __S.getFloat32(0, this)
  }
  setGas(value: number): void {
    __S.setFloat32(0, value, this)
  }
  getBrake(): number {
    return __S.getFloat32(4, this)
  }
  setBrake(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getTorqueOutputCan(): number {
    return __S.getFloat32(32, this)
  }
  setTorqueOutputCan(value: number): void {
    __S.setFloat32(32, value, this)
  }
  getSpeed(): number {
    return __S.getFloat32(24, this)
  }
  setSpeed(value: number): void {
    __S.setFloat32(24, value, this)
  }
  toString(): string {
    return 'CarControl_Actuators_' + super.toString()
  }
}
export class CarControl_CruiseControl extends __S {
  static readonly _capnp = { displayName: 'CruiseControl', id: 'b20e386e0e0ba8d3', size: new __O(16, 0) }
  getCancel(): boolean {
    return __S.getBit(0, this)
  }
  setCancel(value: boolean): void {
    __S.setBit(0, value, this)
  }
  getResume(): boolean {
    return __S.getBit(1, this)
  }
  setResume(value: boolean): void {
    __S.setBit(1, value, this)
  }
  getOverride(): boolean {
    return __S.getBit(2, this)
  }
  setOverride(value: boolean): void {
    __S.setBit(2, value, this)
  }
  getSpeedOverrideDEPRECATED(): number {
    return __S.getFloat32(4, this)
  }
  setSpeedOverrideDEPRECATED(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getAccelOverrideDEPRECATED(): number {
    return __S.getFloat32(8, this)
  }
  setAccelOverrideDEPRECATED(value: number): void {
    __S.setFloat32(8, value, this)
  }
  toString(): string {
    return 'CarControl_CruiseControl_' + super.toString()
  }
}
export enum CarControl_HUDControl_VisualAlert {
  NONE,
  FCW,
  STEER_REQUIRED,
  BRAKE_PRESSED,
  WRONG_GEAR,
  SEATBELT_UNBUCKLED,
  SPEED_TOO_HIGH,
  LDW,
}
export enum CarControl_HUDControl_AudibleAlert {
  NONE,
  ENGAGE,
  DISENGAGE,
  REFUSE,
  WARNING_SOFT,
  WARNING_IMMEDIATE,
  PROMPT,
  PROMPT_REPEAT,
  PROMPT_DISTRACTED,
}
export class CarControl_HUDControl extends __S {
  static readonly VisualAlert = CarControl_HUDControl_VisualAlert
  static readonly AudibleAlert = CarControl_HUDControl_AudibleAlert
  static readonly _capnp = { displayName: 'HUDControl', id: 'd895c87c4eb03a38', size: new __O(16, 0) }
  getSpeedVisible(): boolean {
    return __S.getBit(0, this)
  }
  setSpeedVisible(value: boolean): void {
    __S.setBit(0, value, this)
  }
  getSetSpeed(): number {
    return __S.getFloat32(4, this)
  }
  setSetSpeed(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getLanesVisible(): boolean {
    return __S.getBit(1, this)
  }
  setLanesVisible(value: boolean): void {
    __S.setBit(1, value, this)
  }
  getLeadVisible(): boolean {
    return __S.getBit(2, this)
  }
  setLeadVisible(value: boolean): void {
    __S.setBit(2, value, this)
  }
  getVisualAlert(): CarControl_HUDControl_VisualAlert {
    return __S.getUint16(2, this)
  }
  setVisualAlert(value: CarControl_HUDControl_VisualAlert): void {
    __S.setUint16(2, value, this)
  }
  getRightLaneVisible(): boolean {
    return __S.getBit(3, this)
  }
  setRightLaneVisible(value: boolean): void {
    __S.setBit(3, value, this)
  }
  getLeftLaneVisible(): boolean {
    return __S.getBit(4, this)
  }
  setLeftLaneVisible(value: boolean): void {
    __S.setBit(4, value, this)
  }
  getRightLaneDepart(): boolean {
    return __S.getBit(5, this)
  }
  setRightLaneDepart(value: boolean): void {
    __S.setBit(5, value, this)
  }
  getLeftLaneDepart(): boolean {
    return __S.getBit(6, this)
  }
  setLeftLaneDepart(value: boolean): void {
    __S.setBit(6, value, this)
  }
  getLeadDistanceBars(): number {
    return __S.getInt8(1, this)
  }
  setLeadDistanceBars(value: number): void {
    __S.setInt8(1, value, this)
  }
  getAudibleAlert(): CarControl_HUDControl_AudibleAlert {
    return __S.getUint16(8, this)
  }
  setAudibleAlert(value: CarControl_HUDControl_AudibleAlert): void {
    __S.setUint16(8, value, this)
  }
  toString(): string {
    return 'CarControl_HUDControl_' + super.toString()
  }
}
export class CarControl extends __S {
  static readonly Actuators = CarControl_Actuators
  static readonly CruiseControl = CarControl_CruiseControl
  static readonly HUDControl = CarControl_HUDControl
  static readonly _capnp = { displayName: 'CarControl', id: 'f78829049ab814af', size: new __O(32, 6) }
  getEnabled(): boolean {
    return __S.getBit(0, this)
  }
  setEnabled(value: boolean): void {
    __S.setBit(0, value, this)
  }
  getLatActive(): boolean {
    return __S.getBit(2, this)
  }
  setLatActive(value: boolean): void {
    __S.setBit(2, value, this)
  }
  getLongActive(): boolean {
    return __S.getBit(3, this)
  }
  setLongActive(value: boolean): void {
    __S.setBit(3, value, this)
  }
  adoptActuators(value: capnp.Orphan<CarControl_Actuators>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownActuators(): capnp.Orphan<CarControl_Actuators> {
    return __S.disown(this.getActuators())
  }
  getActuators(): CarControl_Actuators {
    return __S.getStruct(2, CarControl_Actuators, this)
  }
  hasActuators(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initActuators(): CarControl_Actuators {
    return __S.initStructAt(2, CarControl_Actuators, this)
  }
  setActuators(value: CarControl_Actuators): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  getLeftBlinker(): boolean {
    return __S.getBit(4, this)
  }
  setLeftBlinker(value: boolean): void {
    __S.setBit(4, value, this)
  }
  getRightBlinker(): boolean {
    return __S.getBit(5, this)
  }
  setRightBlinker(value: boolean): void {
    __S.setBit(5, value, this)
  }
  adoptOrientationNED(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(4, this))
  }
  disownOrientationNED(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getOrientationNED())
  }
  getOrientationNED(): capnp.List<number> {
    return __S.getList(4, capnp.Float32List, this)
  }
  hasOrientationNED(): boolean {
    return !__S.isNull(__S.getPointer(4, this))
  }
  initOrientationNED(length: number): capnp.List<number> {
    return __S.initList(4, capnp.Float32List, length, this)
  }
  setOrientationNED(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(4, this))
  }
  adoptAngularVelocity(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(5, this))
  }
  disownAngularVelocity(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getAngularVelocity())
  }
  getAngularVelocity(): capnp.List<number> {
    return __S.getList(5, capnp.Float32List, this)
  }
  hasAngularVelocity(): boolean {
    return !__S.isNull(__S.getPointer(5, this))
  }
  initAngularVelocity(length: number): capnp.List<number> {
    return __S.initList(5, capnp.Float32List, length, this)
  }
  setAngularVelocity(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(5, this))
  }
  getCurrentCurvature(): number {
    return __S.getFloat32(24, this)
  }
  setCurrentCurvature(value: number): void {
    __S.setFloat32(24, value, this)
  }
  adoptCruiseControl(value: capnp.Orphan<CarControl_CruiseControl>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownCruiseControl(): capnp.Orphan<CarControl_CruiseControl> {
    return __S.disown(this.getCruiseControl())
  }
  getCruiseControl(): CarControl_CruiseControl {
    return __S.getStruct(0, CarControl_CruiseControl, this)
  }
  hasCruiseControl(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initCruiseControl(): CarControl_CruiseControl {
    return __S.initStructAt(0, CarControl_CruiseControl, this)
  }
  setCruiseControl(value: CarControl_CruiseControl): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptHudControl(value: capnp.Orphan<CarControl_HUDControl>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownHudControl(): capnp.Orphan<CarControl_HUDControl> {
    return __S.disown(this.getHudControl())
  }
  getHudControl(): CarControl_HUDControl {
    return __S.getStruct(1, CarControl_HUDControl, this)
  }
  hasHudControl(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initHudControl(): CarControl_HUDControl {
    return __S.initStructAt(1, CarControl_HUDControl, this)
  }
  setHudControl(value: CarControl_HUDControl): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  getGasDEPRECATED(): number {
    return __S.getFloat32(4, this)
  }
  setGasDEPRECATED(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getBrakeDEPRECATED(): number {
    return __S.getFloat32(8, this)
  }
  setBrakeDEPRECATED(value: number): void {
    __S.setFloat32(8, value, this)
  }
  getSteeringTorqueDEPRECATED(): number {
    return __S.getFloat32(12, this)
  }
  setSteeringTorqueDEPRECATED(value: number): void {
    __S.setFloat32(12, value, this)
  }
  getActiveDEPRECATED(): boolean {
    return __S.getBit(1, this)
  }
  setActiveDEPRECATED(value: boolean): void {
    __S.setBit(1, value, this)
  }
  getRollDEPRECATED(): number {
    return __S.getFloat32(16, this)
  }
  setRollDEPRECATED(value: number): void {
    __S.setFloat32(16, value, this)
  }
  getPitchDEPRECATED(): number {
    return __S.getFloat32(20, this)
  }
  setPitchDEPRECATED(value: number): void {
    __S.setFloat32(20, value, this)
  }
  adoptActuatorsOutputDEPRECATED(value: capnp.Orphan<CarControl_Actuators>): void {
    __S.adopt(value, __S.getPointer(3, this))
  }
  disownActuatorsOutputDEPRECATED(): capnp.Orphan<CarControl_Actuators> {
    return __S.disown(this.getActuatorsOutputDEPRECATED())
  }
  getActuatorsOutputDEPRECATED(): CarControl_Actuators {
    return __S.getStruct(3, CarControl_Actuators, this)
  }
  hasActuatorsOutputDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(3, this))
  }
  initActuatorsOutputDEPRECATED(): CarControl_Actuators {
    return __S.initStructAt(3, CarControl_Actuators, this)
  }
  setActuatorsOutputDEPRECATED(value: CarControl_Actuators): void {
    __S.copyFrom(value, __S.getPointer(3, this))
  }
  toString(): string {
    return 'CarControl_' + super.toString()
  }
}
export class CarOutput extends __S {
  static readonly _capnp = { displayName: 'CarOutput', id: 'd817d6655115ca85', size: new __O(0, 1) }
  adoptActuatorsOutput(value: capnp.Orphan<CarControl_Actuators>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownActuatorsOutput(): capnp.Orphan<CarControl_Actuators> {
    return __S.disown(this.getActuatorsOutput())
  }
  getActuatorsOutput(): CarControl_Actuators {
    return __S.getStruct(0, CarControl_Actuators, this)
  }
  hasActuatorsOutput(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initActuatorsOutput(): CarControl_Actuators {
    return __S.initStructAt(0, CarControl_Actuators, this)
  }
  setActuatorsOutput(value: CarControl_Actuators): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  toString(): string {
    return 'CarOutput_' + super.toString()
  }
}
export class CarParams_SafetyConfig extends __S {
  static readonly _capnp = { displayName: 'SafetyConfig', id: 'e836349c6056b0c9', size: new __O(16, 0) }
  getSafetyModel(): CarParams_SafetyModel {
    return __S.getUint16(0, this)
  }
  setSafetyModel(value: CarParams_SafetyModel): void {
    __S.setUint16(0, value, this)
  }
  getSafetyParam(): number {
    return __S.getUint16(8, this)
  }
  setSafetyParam(value: number): void {
    __S.setUint16(8, value, this)
  }
  getSafetyParamDEPRECATED(): number {
    return __S.getInt16(2, this)
  }
  setSafetyParamDEPRECATED(value: number): void {
    __S.setInt16(2, value, this)
  }
  getSafetyParam2DEPRECATED(): number {
    return __S.getUint32(4, this)
  }
  setSafetyParam2DEPRECATED(value: number): void {
    __S.setUint32(4, value, this)
  }
  toString(): string {
    return 'CarParams_SafetyConfig_' + super.toString()
  }
}
export class CarParams_LateralParams extends __S {
  static readonly _capnp = { displayName: 'LateralParams', id: 'b581b23b1c89dda3', size: new __O(0, 2) }
  adoptTorqueBP(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownTorqueBP(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getTorqueBP())
  }
  getTorqueBP(): capnp.List<number> {
    return __S.getList(0, capnp.Int32List, this)
  }
  hasTorqueBP(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initTorqueBP(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Int32List, length, this)
  }
  setTorqueBP(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptTorqueV(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownTorqueV(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getTorqueV())
  }
  getTorqueV(): capnp.List<number> {
    return __S.getList(1, capnp.Int32List, this)
  }
  hasTorqueV(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initTorqueV(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Int32List, length, this)
  }
  setTorqueV(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  toString(): string {
    return 'CarParams_LateralParams_' + super.toString()
  }
}
export class CarParams_LateralPIDTuning extends __S {
  static readonly _capnp = { displayName: 'LateralPIDTuning', id: '9622723fcbd14c2e', size: new __O(8, 4) }
  adoptKpBP(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownKpBP(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getKpBP())
  }
  getKpBP(): capnp.List<number> {
    return __S.getList(0, capnp.Float32List, this)
  }
  hasKpBP(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initKpBP(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float32List, length, this)
  }
  setKpBP(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptKpV(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownKpV(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getKpV())
  }
  getKpV(): capnp.List<number> {
    return __S.getList(1, capnp.Float32List, this)
  }
  hasKpV(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initKpV(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Float32List, length, this)
  }
  setKpV(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  adoptKiBP(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownKiBP(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getKiBP())
  }
  getKiBP(): capnp.List<number> {
    return __S.getList(2, capnp.Float32List, this)
  }
  hasKiBP(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initKiBP(length: number): capnp.List<number> {
    return __S.initList(2, capnp.Float32List, length, this)
  }
  setKiBP(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  adoptKiV(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(3, this))
  }
  disownKiV(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getKiV())
  }
  getKiV(): capnp.List<number> {
    return __S.getList(3, capnp.Float32List, this)
  }
  hasKiV(): boolean {
    return !__S.isNull(__S.getPointer(3, this))
  }
  initKiV(length: number): capnp.List<number> {
    return __S.initList(3, capnp.Float32List, length, this)
  }
  setKiV(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(3, this))
  }
  getKf(): number {
    return __S.getFloat32(0, this)
  }
  setKf(value: number): void {
    __S.setFloat32(0, value, this)
  }
  toString(): string {
    return 'CarParams_LateralPIDTuning_' + super.toString()
  }
}
export class CarParams_LateralTorqueTuning extends __S {
  static readonly _capnp = { displayName: 'LateralTorqueTuning', id: '80366e0e804ecc1d', size: new __O(40, 0) }
  getFriction(): number {
    return __S.getFloat32(12, this)
  }
  setFriction(value: number): void {
    __S.setFloat32(12, value, this)
  }
  getSteeringAngleDeadzoneDeg(): number {
    return __S.getFloat32(20, this)
  }
  setSteeringAngleDeadzoneDeg(value: number): void {
    __S.setFloat32(20, value, this)
  }
  getLatAccelFactor(): number {
    return __S.getFloat32(24, this)
  }
  setLatAccelFactor(value: number): void {
    __S.setFloat32(24, value, this)
  }
  getLatAccelOffset(): number {
    return __S.getFloat32(28, this)
  }
  setLatAccelOffset(value: number): void {
    __S.setFloat32(28, value, this)
  }
  getUseSteeringAngleDEPRECATED(): boolean {
    return __S.getBit(0, this)
  }
  setUseSteeringAngleDEPRECATED(value: boolean): void {
    __S.setBit(0, value, this)
  }
  getKpDEPRECATED(): number {
    return __S.getFloat32(4, this)
  }
  setKpDEPRECATED(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getKiDEPRECATED(): number {
    return __S.getFloat32(8, this)
  }
  setKiDEPRECATED(value: number): void {
    __S.setFloat32(8, value, this)
  }
  getKfDEPRECATED(): number {
    return __S.getFloat32(16, this)
  }
  setKfDEPRECATED(value: number): void {
    __S.setFloat32(16, value, this)
  }
  getKdDEPRECATED(): number {
    return __S.getFloat32(32, this)
  }
  setKdDEPRECATED(value: number): void {
    __S.setFloat32(32, value, this)
  }
  toString(): string {
    return 'CarParams_LateralTorqueTuning_' + super.toString()
  }
}
export class CarParams_LongitudinalPIDTuning extends __S {
  static readonly _capnp = { displayName: 'LongitudinalPIDTuning', id: 'c342cefc303e9b8e', size: new __O(8, 6) }
  adoptKpBP(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownKpBP(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getKpBP())
  }
  getKpBP(): capnp.List<number> {
    return __S.getList(0, capnp.Float32List, this)
  }
  hasKpBP(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initKpBP(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float32List, length, this)
  }
  setKpBP(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptKpV(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownKpV(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getKpV())
  }
  getKpV(): capnp.List<number> {
    return __S.getList(1, capnp.Float32List, this)
  }
  hasKpV(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initKpV(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Float32List, length, this)
  }
  setKpV(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  adoptKiBP(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownKiBP(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getKiBP())
  }
  getKiBP(): capnp.List<number> {
    return __S.getList(2, capnp.Float32List, this)
  }
  hasKiBP(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initKiBP(length: number): capnp.List<number> {
    return __S.initList(2, capnp.Float32List, length, this)
  }
  setKiBP(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  adoptKiV(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(3, this))
  }
  disownKiV(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getKiV())
  }
  getKiV(): capnp.List<number> {
    return __S.getList(3, capnp.Float32List, this)
  }
  hasKiV(): boolean {
    return !__S.isNull(__S.getPointer(3, this))
  }
  initKiV(length: number): capnp.List<number> {
    return __S.initList(3, capnp.Float32List, length, this)
  }
  setKiV(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(3, this))
  }
  getKfDEPRECATED(): number {
    return __S.getFloat32(0, this)
  }
  setKfDEPRECATED(value: number): void {
    __S.setFloat32(0, value, this)
  }
  adoptDeadzoneBPDEPRECATED(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(4, this))
  }
  disownDeadzoneBPDEPRECATED(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getDeadzoneBPDEPRECATED())
  }
  getDeadzoneBPDEPRECATED(): capnp.List<number> {
    return __S.getList(4, capnp.Float32List, this)
  }
  hasDeadzoneBPDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(4, this))
  }
  initDeadzoneBPDEPRECATED(length: number): capnp.List<number> {
    return __S.initList(4, capnp.Float32List, length, this)
  }
  setDeadzoneBPDEPRECATED(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(4, this))
  }
  adoptDeadzoneVDEPRECATED(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(5, this))
  }
  disownDeadzoneVDEPRECATED(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getDeadzoneVDEPRECATED())
  }
  getDeadzoneVDEPRECATED(): capnp.List<number> {
    return __S.getList(5, capnp.Float32List, this)
  }
  hasDeadzoneVDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(5, this))
  }
  initDeadzoneVDEPRECATED(length: number): capnp.List<number> {
    return __S.initList(5, capnp.Float32List, length, this)
  }
  setDeadzoneVDEPRECATED(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(5, this))
  }
  toString(): string {
    return 'CarParams_LongitudinalPIDTuning_' + super.toString()
  }
}
export class CarParams_LateralINDITuning extends __S {
  static readonly _capnp = { displayName: 'LateralINDITuning', id: 'a334472e045533b3', size: new __O(16, 8) }
  adoptOuterLoopGainBP(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownOuterLoopGainBP(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getOuterLoopGainBP())
  }
  getOuterLoopGainBP(): capnp.List<number> {
    return __S.getList(0, capnp.Float32List, this)
  }
  hasOuterLoopGainBP(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initOuterLoopGainBP(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float32List, length, this)
  }
  setOuterLoopGainBP(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptOuterLoopGainV(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownOuterLoopGainV(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getOuterLoopGainV())
  }
  getOuterLoopGainV(): capnp.List<number> {
    return __S.getList(1, capnp.Float32List, this)
  }
  hasOuterLoopGainV(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initOuterLoopGainV(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Float32List, length, this)
  }
  setOuterLoopGainV(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  adoptInnerLoopGainBP(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownInnerLoopGainBP(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getInnerLoopGainBP())
  }
  getInnerLoopGainBP(): capnp.List<number> {
    return __S.getList(2, capnp.Float32List, this)
  }
  hasInnerLoopGainBP(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initInnerLoopGainBP(length: number): capnp.List<number> {
    return __S.initList(2, capnp.Float32List, length, this)
  }
  setInnerLoopGainBP(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  adoptInnerLoopGainV(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(3, this))
  }
  disownInnerLoopGainV(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getInnerLoopGainV())
  }
  getInnerLoopGainV(): capnp.List<number> {
    return __S.getList(3, capnp.Float32List, this)
  }
  hasInnerLoopGainV(): boolean {
    return !__S.isNull(__S.getPointer(3, this))
  }
  initInnerLoopGainV(length: number): capnp.List<number> {
    return __S.initList(3, capnp.Float32List, length, this)
  }
  setInnerLoopGainV(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(3, this))
  }
  adoptTimeConstantBP(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(4, this))
  }
  disownTimeConstantBP(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getTimeConstantBP())
  }
  getTimeConstantBP(): capnp.List<number> {
    return __S.getList(4, capnp.Float32List, this)
  }
  hasTimeConstantBP(): boolean {
    return !__S.isNull(__S.getPointer(4, this))
  }
  initTimeConstantBP(length: number): capnp.List<number> {
    return __S.initList(4, capnp.Float32List, length, this)
  }
  setTimeConstantBP(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(4, this))
  }
  adoptTimeConstantV(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(5, this))
  }
  disownTimeConstantV(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getTimeConstantV())
  }
  getTimeConstantV(): capnp.List<number> {
    return __S.getList(5, capnp.Float32List, this)
  }
  hasTimeConstantV(): boolean {
    return !__S.isNull(__S.getPointer(5, this))
  }
  initTimeConstantV(length: number): capnp.List<number> {
    return __S.initList(5, capnp.Float32List, length, this)
  }
  setTimeConstantV(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(5, this))
  }
  adoptActuatorEffectivenessBP(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(6, this))
  }
  disownActuatorEffectivenessBP(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getActuatorEffectivenessBP())
  }
  getActuatorEffectivenessBP(): capnp.List<number> {
    return __S.getList(6, capnp.Float32List, this)
  }
  hasActuatorEffectivenessBP(): boolean {
    return !__S.isNull(__S.getPointer(6, this))
  }
  initActuatorEffectivenessBP(length: number): capnp.List<number> {
    return __S.initList(6, capnp.Float32List, length, this)
  }
  setActuatorEffectivenessBP(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(6, this))
  }
  adoptActuatorEffectivenessV(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(7, this))
  }
  disownActuatorEffectivenessV(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getActuatorEffectivenessV())
  }
  getActuatorEffectivenessV(): capnp.List<number> {
    return __S.getList(7, capnp.Float32List, this)
  }
  hasActuatorEffectivenessV(): boolean {
    return !__S.isNull(__S.getPointer(7, this))
  }
  initActuatorEffectivenessV(length: number): capnp.List<number> {
    return __S.initList(7, capnp.Float32List, length, this)
  }
  setActuatorEffectivenessV(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(7, this))
  }
  getOuterLoopGainDEPRECATED(): number {
    return __S.getFloat32(0, this)
  }
  setOuterLoopGainDEPRECATED(value: number): void {
    __S.setFloat32(0, value, this)
  }
  getInnerLoopGainDEPRECATED(): number {
    return __S.getFloat32(4, this)
  }
  setInnerLoopGainDEPRECATED(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getTimeConstantDEPRECATED(): number {
    return __S.getFloat32(8, this)
  }
  setTimeConstantDEPRECATED(value: number): void {
    __S.setFloat32(8, value, this)
  }
  getActuatorEffectivenessDEPRECATED(): number {
    return __S.getFloat32(12, this)
  }
  setActuatorEffectivenessDEPRECATED(value: number): void {
    __S.setFloat32(12, value, this)
  }
  toString(): string {
    return 'CarParams_LateralINDITuning_' + super.toString()
  }
}
export class CarParams_LateralLQRTuning extends __S {
  static readonly _capnp = { displayName: 'LateralLQRTuning', id: '9d151e3f28616a12', size: new __O(16, 5) }
  getScale(): number {
    return __S.getFloat32(0, this)
  }
  setScale(value: number): void {
    __S.setFloat32(0, value, this)
  }
  getKi(): number {
    return __S.getFloat32(4, this)
  }
  setKi(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getDcGain(): number {
    return __S.getFloat32(8, this)
  }
  setDcGain(value: number): void {
    __S.setFloat32(8, value, this)
  }
  adoptA(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownA(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getA())
  }
  getA(): capnp.List<number> {
    return __S.getList(0, capnp.Float32List, this)
  }
  hasA(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initA(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float32List, length, this)
  }
  setA(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptB(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownB(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getB())
  }
  getB(): capnp.List<number> {
    return __S.getList(1, capnp.Float32List, this)
  }
  hasB(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initB(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Float32List, length, this)
  }
  setB(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  adoptC(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownC(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getC())
  }
  getC(): capnp.List<number> {
    return __S.getList(2, capnp.Float32List, this)
  }
  hasC(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initC(length: number): capnp.List<number> {
    return __S.initList(2, capnp.Float32List, length, this)
  }
  setC(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  adoptK(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(3, this))
  }
  disownK(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getK())
  }
  getK(): capnp.List<number> {
    return __S.getList(3, capnp.Float32List, this)
  }
  hasK(): boolean {
    return !__S.isNull(__S.getPointer(3, this))
  }
  initK(length: number): capnp.List<number> {
    return __S.initList(3, capnp.Float32List, length, this)
  }
  setK(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(3, this))
  }
  adoptL(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(4, this))
  }
  disownL(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getL())
  }
  getL(): capnp.List<number> {
    return __S.getList(4, capnp.Float32List, this)
  }
  hasL(): boolean {
    return !__S.isNull(__S.getPointer(4, this))
  }
  initL(length: number): capnp.List<number> {
    return __S.initList(4, capnp.Float32List, length, this)
  }
  setL(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(4, this))
  }
  toString(): string {
    return 'CarParams_LateralLQRTuning_' + super.toString()
  }
}
export enum CarParams_SafetyModel {
  SILENT,
  HONDA_NIDEC,
  TOYOTA,
  ELM327,
  GM,
  HONDA_BOSCH_GIRAFFE,
  FORD,
  CADILLAC,
  HYUNDAI,
  CHRYSLER,
  TESLA,
  SUBARU,
  GM_PASSIVE,
  MAZDA,
  NISSAN,
  VOLKSWAGEN,
  TOYOTA_IPAS,
  ALL_OUTPUT,
  GM_ASCM,
  NO_OUTPUT,
  HONDA_BOSCH,
  VOLKSWAGEN_PQ,
  SUBARU_PREGLOBAL,
  HYUNDAI_LEGACY,
  HYUNDAI_COMMUNITY,
  VOLKSWAGEN_MLB,
  HONGQI,
  BODY,
  HYUNDAI_CANFD,
  VOLKSWAGEN_MQB_EVO,
  CHRYSLER_CUSW,
  PSA,
  FCA_GIORGIO,
  RIVIAN,
  VOLKSWAGEN_MEB,
}
export enum CarParams_SteerControlType {
  TORQUE,
  ANGLE,
  CURVATURE_DEPRECATED,
}
export enum CarParams_TransmissionType {
  UNKNOWN,
  AUTOMATIC,
  MANUAL,
  DIRECT,
  CVT,
}
export class CarParams_CarFw extends __S {
  static readonly _capnp = { displayName: 'CarFw', id: '962b56180c9359ce', size: new __O(16, 3) }
  getEcu(): CarParams_Ecu {
    return __S.getUint16(0, this)
  }
  setEcu(value: CarParams_Ecu): void {
    __S.setUint16(0, value, this)
  }
  adoptFwVersion(value: capnp.Orphan<capnp.Data>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownFwVersion(): capnp.Orphan<capnp.Data> {
    return __S.disown(this.getFwVersion())
  }
  getFwVersion(): capnp.Data {
    return __S.getData(0, this)
  }
  hasFwVersion(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initFwVersion(length: number): capnp.Data {
    return __S.initData(0, length, this)
  }
  setFwVersion(value: capnp.Data): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  getAddress(): number {
    return __S.getUint32(4, this)
  }
  setAddress(value: number): void {
    __S.setUint32(4, value, this)
  }
  getSubAddress(): number {
    return __S.getUint8(2, this)
  }
  setSubAddress(value: number): void {
    __S.setUint8(2, value, this)
  }
  getResponseAddress(): number {
    return __S.getUint32(8, this)
  }
  setResponseAddress(value: number): void {
    __S.setUint32(8, value, this)
  }
  adoptRequest(value: capnp.Orphan<capnp.List<capnp.Data>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownRequest(): capnp.Orphan<capnp.List<capnp.Data>> {
    return __S.disown(this.getRequest())
  }
  getRequest(): capnp.List<capnp.Data> {
    return __S.getList(1, capnp.DataList, this)
  }
  hasRequest(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initRequest(length: number): capnp.List<capnp.Data> {
    return __S.initList(1, capnp.DataList, length, this)
  }
  setRequest(value: capnp.List<capnp.Data>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  getBrand(): string {
    return __S.getText(2, this)
  }
  setBrand(value: string): void {
    __S.setText(2, value, this)
  }
  getBus(): number {
    return __S.getUint8(3, this)
  }
  setBus(value: number): void {
    __S.setUint8(3, value, this)
  }
  getLogging(): boolean {
    return __S.getBit(96, this)
  }
  setLogging(value: boolean): void {
    __S.setBit(96, value, this)
  }
  getObdMultiplexing(): boolean {
    return __S.getBit(97, this)
  }
  setObdMultiplexing(value: boolean): void {
    __S.setBit(97, value, this)
  }
  toString(): string {
    return 'CarParams_CarFw_' + super.toString()
  }
}
export enum CarParams_Ecu {
  EPS,
  ABS,
  FWD_RADAR,
  FWD_CAMERA,
  ENGINE,
  UNKNOWN,
  TRANSMISSION,
  HYBRID,
  SRS,
  GATEWAY,
  HUD,
  COMBINATION_METER,
  ELECTRIC_BRAKE_BOOSTER,
  SHIFT_BY_WIRE,
  ADAS,
  CORNER_RADAR,
  HVAC,
  PARKING_ADAS,
  EPB,
  TELEMATICS,
  BODY,
  DSU,
  VSA,
  PROGRAMMED_FUEL_INJECTION,
  DEBUG,
}
export enum CarParams_FingerprintSource {
  CAN,
  FW,
  FIXED,
}
export enum CarParams_NetworkLocation {
  FWD_CAMERA,
  GATEWAY,
}
export enum CarParams_LateralTuning_Which {
  PID = 0,
  INDI_DEPRECATED = 1,
  LQR_DEPRECATED = 2,
  TORQUE = 3,
}
export class CarParams_LateralTuning extends __S {
  static readonly PID = CarParams_LateralTuning_Which.PID
  static readonly INDI_DEPRECATED = CarParams_LateralTuning_Which.INDI_DEPRECATED
  static readonly LQR_DEPRECATED = CarParams_LateralTuning_Which.LQR_DEPRECATED
  static readonly TORQUE = CarParams_LateralTuning_Which.TORQUE
  static readonly _capnp = { displayName: 'lateralTuning', id: '93fc580a35339568', size: new __O(144, 14) }
  adoptPid(value: capnp.Orphan<CarParams_LateralPIDTuning>): void {
    __S.setUint16(14, 0, this)
    __S.adopt(value, __S.getPointer(9, this))
  }
  disownPid(): capnp.Orphan<CarParams_LateralPIDTuning> {
    return __S.disown(this.getPid())
  }
  getPid(): CarParams_LateralPIDTuning {
    __S.testWhich('pid', __S.getUint16(14, this), 0, this)
    return __S.getStruct(9, CarParams_LateralPIDTuning, this)
  }
  hasPid(): boolean {
    return !__S.isNull(__S.getPointer(9, this))
  }
  initPid(): CarParams_LateralPIDTuning {
    __S.setUint16(14, 0, this)
    return __S.initStructAt(9, CarParams_LateralPIDTuning, this)
  }
  isPid(): boolean {
    return __S.getUint16(14, this) === 0
  }
  setPid(value: CarParams_LateralPIDTuning): void {
    __S.setUint16(14, 0, this)
    __S.copyFrom(value, __S.getPointer(9, this))
  }
  adoptIndiDEPRECATED(value: capnp.Orphan<CarParams_LateralINDITuning>): void {
    __S.setUint16(14, 1, this)
    __S.adopt(value, __S.getPointer(9, this))
  }
  disownIndiDEPRECATED(): capnp.Orphan<CarParams_LateralINDITuning> {
    return __S.disown(this.getIndiDEPRECATED())
  }
  getIndiDEPRECATED(): CarParams_LateralINDITuning {
    __S.testWhich('indiDEPRECATED', __S.getUint16(14, this), 1, this)
    return __S.getStruct(9, CarParams_LateralINDITuning, this)
  }
  hasIndiDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(9, this))
  }
  initIndiDEPRECATED(): CarParams_LateralINDITuning {
    __S.setUint16(14, 1, this)
    return __S.initStructAt(9, CarParams_LateralINDITuning, this)
  }
  isIndiDEPRECATED(): boolean {
    return __S.getUint16(14, this) === 1
  }
  setIndiDEPRECATED(value: CarParams_LateralINDITuning): void {
    __S.setUint16(14, 1, this)
    __S.copyFrom(value, __S.getPointer(9, this))
  }
  adoptLqrDEPRECATED(value: capnp.Orphan<CarParams_LateralLQRTuning>): void {
    __S.setUint16(14, 2, this)
    __S.adopt(value, __S.getPointer(9, this))
  }
  disownLqrDEPRECATED(): capnp.Orphan<CarParams_LateralLQRTuning> {
    return __S.disown(this.getLqrDEPRECATED())
  }
  getLqrDEPRECATED(): CarParams_LateralLQRTuning {
    __S.testWhich('lqrDEPRECATED', __S.getUint16(14, this), 2, this)
    return __S.getStruct(9, CarParams_LateralLQRTuning, this)
  }
  hasLqrDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(9, this))
  }
  initLqrDEPRECATED(): CarParams_LateralLQRTuning {
    __S.setUint16(14, 2, this)
    return __S.initStructAt(9, CarParams_LateralLQRTuning, this)
  }
  isLqrDEPRECATED(): boolean {
    return __S.getUint16(14, this) === 2
  }
  setLqrDEPRECATED(value: CarParams_LateralLQRTuning): void {
    __S.setUint16(14, 2, this)
    __S.copyFrom(value, __S.getPointer(9, this))
  }
  adoptTorque(value: capnp.Orphan<CarParams_LateralTorqueTuning>): void {
    __S.setUint16(14, 3, this)
    __S.adopt(value, __S.getPointer(9, this))
  }
  disownTorque(): capnp.Orphan<CarParams_LateralTorqueTuning> {
    return __S.disown(this.getTorque())
  }
  getTorque(): CarParams_LateralTorqueTuning {
    __S.testWhich('torque', __S.getUint16(14, this), 3, this)
    return __S.getStruct(9, CarParams_LateralTorqueTuning, this)
  }
  hasTorque(): boolean {
    return !__S.isNull(__S.getPointer(9, this))
  }
  initTorque(): CarParams_LateralTorqueTuning {
    __S.setUint16(14, 3, this)
    return __S.initStructAt(9, CarParams_LateralTorqueTuning, this)
  }
  isTorque(): boolean {
    return __S.getUint16(14, this) === 3
  }
  setTorque(value: CarParams_LateralTorqueTuning): void {
    __S.setUint16(14, 3, this)
    __S.copyFrom(value, __S.getPointer(9, this))
  }
  toString(): string {
    return 'CarParams_LateralTuning_' + super.toString()
  }
  which(): CarParams_LateralTuning_Which {
    return __S.getUint16(14, this)
  }
}
export class CarParams extends __S {
  static readonly SafetyConfig = CarParams_SafetyConfig
  static readonly LateralParams = CarParams_LateralParams
  static readonly LateralPIDTuning = CarParams_LateralPIDTuning
  static readonly LateralTorqueTuning = CarParams_LateralTorqueTuning
  static readonly LongitudinalPIDTuning = CarParams_LongitudinalPIDTuning
  static readonly LateralINDITuning = CarParams_LateralINDITuning
  static readonly LateralLQRTuning = CarParams_LateralLQRTuning
  static readonly SafetyModel = CarParams_SafetyModel
  static readonly SteerControlType = CarParams_SteerControlType
  static readonly TransmissionType = CarParams_TransmissionType
  static readonly CarFw = CarParams_CarFw
  static readonly Ecu = CarParams_Ecu
  static readonly FingerprintSource = CarParams_FingerprintSource
  static readonly NetworkLocation = CarParams_NetworkLocation
  static readonly _capnp = {
    displayName: 'CarParams',
    id: '8c69372490aaa9da',
    size: new __O(144, 14),
    defaultSafetyModelPassiveDEPRECATED: capnp.getUint16Mask(0),
    defaultRadarTimeStepDEPRECATED: capnp.getFloat32Mask(0.05000000074505806),
  }
  static _SafetyConfigs: capnp.ListCtor<CarParams_SafetyConfig>
  static _CarFw: capnp.ListCtor<CarParams_CarFw>
  getBrand(): string {
    return __S.getText(0, this)
  }
  setBrand(value: string): void {
    __S.setText(0, value, this)
  }
  getCarFingerprint(): string {
    return __S.getText(1, this)
  }
  setCarFingerprint(value: string): void {
    __S.setText(1, value, this)
  }
  getFuzzyFingerprint(): boolean {
    return __S.getBit(13, this)
  }
  setFuzzyFingerprint(value: boolean): void {
    __S.setBit(13, value, this)
  }
  getNotCar(): boolean {
    return __S.getBit(992, this)
  }
  setNotCar(value: boolean): void {
    __S.setBit(992, value, this)
  }
  getPcmCruise(): boolean {
    return __S.getBit(1, this)
  }
  setPcmCruise(value: boolean): void {
    __S.setBit(1, value, this)
  }
  getEnableDsu(): boolean {
    return __S.getBit(3, this)
  }
  setEnableDsu(value: boolean): void {
    __S.setBit(3, value, this)
  }
  getEnableBsm(): boolean {
    return __S.getBit(14, this)
  }
  setEnableBsm(value: boolean): void {
    __S.setBit(14, value, this)
  }
  getFlags(): number {
    return __S.getUint32(120, this)
  }
  setFlags(value: number): void {
    __S.setUint32(120, value, this)
  }
  getAlphaLongitudinalAvailable(): boolean {
    return __S.getBit(995, this)
  }
  setAlphaLongitudinalAvailable(value: boolean): void {
    __S.setBit(995, value, this)
  }
  getMinEnableSpeed(): number {
    return __S.getFloat32(4, this)
  }
  setMinEnableSpeed(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getMinSteerSpeed(): number {
    return __S.getFloat32(8, this)
  }
  setMinSteerSpeed(value: number): void {
    __S.setFloat32(8, value, this)
  }
  getSteerAtStandstill(): boolean {
    return __S.getBit(999, this)
  }
  setSteerAtStandstill(value: boolean): void {
    __S.setBit(999, value, this)
  }
  adoptSafetyConfigs(value: capnp.Orphan<capnp.List<CarParams_SafetyConfig>>): void {
    __S.adopt(value, __S.getPointer(13, this))
  }
  disownSafetyConfigs(): capnp.Orphan<capnp.List<CarParams_SafetyConfig>> {
    return __S.disown(this.getSafetyConfigs())
  }
  getSafetyConfigs(): capnp.List<CarParams_SafetyConfig> {
    return __S.getList(13, CarParams._SafetyConfigs, this)
  }
  hasSafetyConfigs(): boolean {
    return !__S.isNull(__S.getPointer(13, this))
  }
  initSafetyConfigs(length: number): capnp.List<CarParams_SafetyConfig> {
    return __S.initList(13, CarParams._SafetyConfigs, length, this)
  }
  setSafetyConfigs(value: capnp.List<CarParams_SafetyConfig>): void {
    __S.copyFrom(value, __S.getPointer(13, this))
  }
  getAlternativeExperience(): number {
    return __S.getInt16(82, this)
  }
  setAlternativeExperience(value: number): void {
    __S.setInt16(82, value, this)
  }
  getMaxLateralAccel(): number {
    return __S.getFloat32(128, this)
  }
  setMaxLateralAccel(value: number): void {
    __S.setFloat32(128, value, this)
  }
  getAutoResumeSng(): boolean {
    return __S.getBit(993, this)
  }
  setAutoResumeSng(value: boolean): void {
    __S.setBit(993, value, this)
  }
  getMass(): number {
    return __S.getFloat32(16, this)
  }
  setMass(value: number): void {
    __S.setFloat32(16, value, this)
  }
  getWheelbase(): number {
    return __S.getFloat32(20, this)
  }
  setWheelbase(value: number): void {
    __S.setFloat32(20, value, this)
  }
  getCenterToFront(): number {
    return __S.getFloat32(24, this)
  }
  setCenterToFront(value: number): void {
    __S.setFloat32(24, value, this)
  }
  getSteerRatio(): number {
    return __S.getFloat32(28, this)
  }
  setSteerRatio(value: number): void {
    __S.setFloat32(28, value, this)
  }
  getSteerRatioRear(): number {
    return __S.getFloat32(32, this)
  }
  setSteerRatioRear(value: number): void {
    __S.setFloat32(32, value, this)
  }
  getRotationalInertia(): number {
    return __S.getFloat32(36, this)
  }
  setRotationalInertia(value: number): void {
    __S.setFloat32(36, value, this)
  }
  getTireStiffnessFactor(): number {
    return __S.getFloat32(132, this)
  }
  setTireStiffnessFactor(value: number): void {
    __S.setFloat32(132, value, this)
  }
  getTireStiffnessFront(): number {
    return __S.getFloat32(40, this)
  }
  setTireStiffnessFront(value: number): void {
    __S.setFloat32(40, value, this)
  }
  getTireStiffnessRear(): number {
    return __S.getFloat32(44, this)
  }
  setTireStiffnessRear(value: number): void {
    __S.setFloat32(44, value, this)
  }
  adoptLongitudinalTuning(value: capnp.Orphan<CarParams_LongitudinalPIDTuning>): void {
    __S.adopt(value, __S.getPointer(8, this))
  }
  disownLongitudinalTuning(): capnp.Orphan<CarParams_LongitudinalPIDTuning> {
    return __S.disown(this.getLongitudinalTuning())
  }
  getLongitudinalTuning(): CarParams_LongitudinalPIDTuning {
    return __S.getStruct(8, CarParams_LongitudinalPIDTuning, this)
  }
  hasLongitudinalTuning(): boolean {
    return !__S.isNull(__S.getPointer(8, this))
  }
  initLongitudinalTuning(): CarParams_LongitudinalPIDTuning {
    return __S.initStructAt(8, CarParams_LongitudinalPIDTuning, this)
  }
  setLongitudinalTuning(value: CarParams_LongitudinalPIDTuning): void {
    __S.copyFrom(value, __S.getPointer(8, this))
  }
  adoptLateralParams(value: capnp.Orphan<CarParams_LateralParams>): void {
    __S.adopt(value, __S.getPointer(12, this))
  }
  disownLateralParams(): capnp.Orphan<CarParams_LateralParams> {
    return __S.disown(this.getLateralParams())
  }
  getLateralParams(): CarParams_LateralParams {
    return __S.getStruct(12, CarParams_LateralParams, this)
  }
  hasLateralParams(): boolean {
    return !__S.isNull(__S.getPointer(12, this))
  }
  initLateralParams(): CarParams_LateralParams {
    return __S.initStructAt(12, CarParams_LateralParams, this)
  }
  setLateralParams(value: CarParams_LateralParams): void {
    __S.copyFrom(value, __S.getPointer(12, this))
  }
  getLateralTuning(): CarParams_LateralTuning {
    return __S.getAs(CarParams_LateralTuning, this)
  }
  initLateralTuning(): CarParams_LateralTuning {
    return __S.getAs(CarParams_LateralTuning, this)
  }
  getSteerLimitAlert(): boolean {
    return __S.getBit(5, this)
  }
  setSteerLimitAlert(value: boolean): void {
    __S.setBit(5, value, this)
  }
  getSteerLimitTimer(): number {
    return __S.getFloat32(76, this)
  }
  setSteerLimitTimer(value: number): void {
    __S.setFloat32(76, value, this)
  }
  getVEgoStopping(): number {
    return __S.getFloat32(48, this)
  }
  setVEgoStopping(value: number): void {
    __S.setFloat32(48, value, this)
  }
  getVEgoStarting(): number {
    return __S.getFloat32(104, this)
  }
  setVEgoStarting(value: number): void {
    __S.setFloat32(104, value, this)
  }
  getSteerControlType(): CarParams_SteerControlType {
    return __S.getUint16(60, this)
  }
  setSteerControlType(value: CarParams_SteerControlType): void {
    __S.setUint16(60, value, this)
  }
  getRadarUnavailable(): boolean {
    return __S.getBit(8, this)
  }
  setRadarUnavailable(value: boolean): void {
    __S.setBit(8, value, this)
  }
  getStopAccel(): number {
    return __S.getFloat32(108, this)
  }
  setStopAccel(value: number): void {
    __S.setFloat32(108, value, this)
  }
  getStoppingDecelRate(): number {
    return __S.getFloat32(88, this)
  }
  setStoppingDecelRate(value: number): void {
    __S.setFloat32(88, value, this)
  }
  getStartAccel(): number {
    return __S.getFloat32(52, this)
  }
  setStartAccel(value: number): void {
    __S.setFloat32(52, value, this)
  }
  getStartingState(): boolean {
    return __S.getBit(994, this)
  }
  setStartingState(value: boolean): void {
    __S.setBit(994, value, this)
  }
  getSteerActuatorDelay(): number {
    return __S.getFloat32(64, this)
  }
  setSteerActuatorDelay(value: number): void {
    __S.setFloat32(64, value, this)
  }
  getLongitudinalActuatorDelay(): number {
    return __S.getFloat32(100, this)
  }
  setLongitudinalActuatorDelay(value: number): void {
    __S.setFloat32(100, value, this)
  }
  getOpenpilotLongitudinalControl(): boolean {
    return __S.getBit(9, this)
  }
  setOpenpilotLongitudinalControl(value: boolean): void {
    __S.setBit(9, value, this)
  }
  getCarVin(): string {
    return __S.getText(10, this)
  }
  setCarVin(value: string): void {
    __S.setText(10, value, this)
  }
  getDashcamOnly(): boolean {
    return __S.getBit(11, this)
  }
  setDashcamOnly(value: boolean): void {
    __S.setBit(11, value, this)
  }
  getPassive(): boolean {
    return __S.getBit(996, this)
  }
  setPassive(value: boolean): void {
    __S.setBit(996, value, this)
  }
  getTransmissionType(): CarParams_TransmissionType {
    return __S.getUint16(68, this)
  }
  setTransmissionType(value: CarParams_TransmissionType): void {
    __S.setUint16(68, value, this)
  }
  adoptCarFw(value: capnp.Orphan<capnp.List<CarParams_CarFw>>): void {
    __S.adopt(value, __S.getPointer(11, this))
  }
  disownCarFw(): capnp.Orphan<capnp.List<CarParams_CarFw>> {
    return __S.disown(this.getCarFw())
  }
  getCarFw(): capnp.List<CarParams_CarFw> {
    return __S.getList(11, CarParams._CarFw, this)
  }
  hasCarFw(): boolean {
    return !__S.isNull(__S.getPointer(11, this))
  }
  initCarFw(length: number): capnp.List<CarParams_CarFw> {
    return __S.initList(11, CarParams._CarFw, length, this)
  }
  setCarFw(value: capnp.List<CarParams_CarFw>): void {
    __S.copyFrom(value, __S.getPointer(11, this))
  }
  getRadarDelay(): number {
    return __S.getFloat32(136, this)
  }
  setRadarDelay(value: number): void {
    __S.setFloat32(136, value, this)
  }
  getFingerprintSource(): CarParams_FingerprintSource {
    return __S.getUint16(70, this)
  }
  setFingerprintSource(value: CarParams_FingerprintSource): void {
    __S.setUint16(70, value, this)
  }
  getNetworkLocation(): CarParams_NetworkLocation {
    return __S.getUint16(80, this)
  }
  setNetworkLocation(value: CarParams_NetworkLocation): void {
    __S.setUint16(80, value, this)
  }
  getWheelSpeedFactor(): number {
    return __S.getFloat32(116, this)
  }
  setWheelSpeedFactor(value: number): void {
    __S.setFloat32(116, value, this)
  }
  getSecOcRequired(): boolean {
    return __S.getBit(997, this)
  }
  setSecOcRequired(value: boolean): void {
    __S.setBit(997, value, this)
  }
  getSecOcKeyAvailable(): boolean {
    return __S.getBit(998, this)
  }
  setSecOcKeyAvailable(value: boolean): void {
    __S.setBit(998, value, this)
  }
  getEnableGasInterceptorDEPRECATED(): boolean {
    return __S.getBit(0, this)
  }
  setEnableGasInterceptorDEPRECATED(value: boolean): void {
    __S.setBit(0, value, this)
  }
  getEnableCameraDEPRECATED(): boolean {
    return __S.getBit(2, this)
  }
  setEnableCameraDEPRECATED(value: boolean): void {
    __S.setBit(2, value, this)
  }
  getEnableApgsDEPRECATED(): boolean {
    return __S.getBit(4, this)
  }
  setEnableApgsDEPRECATED(value: boolean): void {
    __S.setBit(4, value, this)
  }
  getSteerRateCostDEPRECATED(): number {
    return __S.getFloat32(56, this)
  }
  setSteerRateCostDEPRECATED(value: number): void {
    __S.setFloat32(56, value, this)
  }
  getIsPandaBlackDEPRECATED(): boolean {
    return __S.getBit(10, this)
  }
  setIsPandaBlackDEPRECATED(value: boolean): void {
    __S.setBit(10, value, this)
  }
  getHasStockCameraDEPRECATED(): boolean {
    return __S.getBit(15, this)
  }
  setHasStockCameraDEPRECATED(value: boolean): void {
    __S.setBit(15, value, this)
  }
  getSafetyParamDEPRECATED(): number {
    return __S.getInt16(12, this)
  }
  setSafetyParamDEPRECATED(value: number): void {
    __S.setInt16(12, value, this)
  }
  getSafetyModelDEPRECATED(): CarParams_SafetyModel {
    return __S.getUint16(2, this)
  }
  setSafetyModelDEPRECATED(value: CarParams_SafetyModel): void {
    __S.setUint16(2, value, this)
  }
  getSafetyModelPassiveDEPRECATED(): CarParams_SafetyModel {
    return __S.getUint16(62, this, CarParams._capnp.defaultSafetyModelPassiveDEPRECATED)
  }
  setSafetyModelPassiveDEPRECATED(value: CarParams_SafetyModel): void {
    __S.setUint16(62, value, this)
  }
  getMinSpeedCanDEPRECATED(): number {
    return __S.getFloat32(84, this)
  }
  setMinSpeedCanDEPRECATED(value: number): void {
    __S.setFloat32(84, value, this)
  }
  getCommunityFeatureDEPRECATED(): boolean {
    return __S.getBit(12, this)
  }
  setCommunityFeatureDEPRECATED(value: boolean): void {
    __S.setBit(12, value, this)
  }
  getStartingAccelRateDEPRECATED(): number {
    return __S.getFloat32(92, this)
  }
  setStartingAccelRateDEPRECATED(value: number): void {
    __S.setFloat32(92, value, this)
  }
  adoptSteerMaxBPDEPRECATED(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownSteerMaxBPDEPRECATED(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getSteerMaxBPDEPRECATED())
  }
  getSteerMaxBPDEPRECATED(): capnp.List<number> {
    return __S.getList(2, capnp.Float32List, this)
  }
  hasSteerMaxBPDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initSteerMaxBPDEPRECATED(length: number): capnp.List<number> {
    return __S.initList(2, capnp.Float32List, length, this)
  }
  setSteerMaxBPDEPRECATED(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  adoptSteerMaxVDEPRECATED(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(3, this))
  }
  disownSteerMaxVDEPRECATED(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getSteerMaxVDEPRECATED())
  }
  getSteerMaxVDEPRECATED(): capnp.List<number> {
    return __S.getList(3, capnp.Float32List, this)
  }
  hasSteerMaxVDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(3, this))
  }
  initSteerMaxVDEPRECATED(length: number): capnp.List<number> {
    return __S.initList(3, capnp.Float32List, length, this)
  }
  setSteerMaxVDEPRECATED(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(3, this))
  }
  adoptGasMaxBPDEPRECATED(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(4, this))
  }
  disownGasMaxBPDEPRECATED(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getGasMaxBPDEPRECATED())
  }
  getGasMaxBPDEPRECATED(): capnp.List<number> {
    return __S.getList(4, capnp.Float32List, this)
  }
  hasGasMaxBPDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(4, this))
  }
  initGasMaxBPDEPRECATED(length: number): capnp.List<number> {
    return __S.initList(4, capnp.Float32List, length, this)
  }
  setGasMaxBPDEPRECATED(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(4, this))
  }
  adoptGasMaxVDEPRECATED(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(5, this))
  }
  disownGasMaxVDEPRECATED(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getGasMaxVDEPRECATED())
  }
  getGasMaxVDEPRECATED(): capnp.List<number> {
    return __S.getList(5, capnp.Float32List, this)
  }
  hasGasMaxVDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(5, this))
  }
  initGasMaxVDEPRECATED(length: number): capnp.List<number> {
    return __S.initList(5, capnp.Float32List, length, this)
  }
  setGasMaxVDEPRECATED(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(5, this))
  }
  adoptBrakeMaxBPDEPRECATED(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(6, this))
  }
  disownBrakeMaxBPDEPRECATED(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getBrakeMaxBPDEPRECATED())
  }
  getBrakeMaxBPDEPRECATED(): capnp.List<number> {
    return __S.getList(6, capnp.Float32List, this)
  }
  hasBrakeMaxBPDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(6, this))
  }
  initBrakeMaxBPDEPRECATED(length: number): capnp.List<number> {
    return __S.initList(6, capnp.Float32List, length, this)
  }
  setBrakeMaxBPDEPRECATED(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(6, this))
  }
  adoptBrakeMaxVDEPRECATED(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(7, this))
  }
  disownBrakeMaxVDEPRECATED(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getBrakeMaxVDEPRECATED())
  }
  getBrakeMaxVDEPRECATED(): capnp.List<number> {
    return __S.getList(7, capnp.Float32List, this)
  }
  hasBrakeMaxVDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(7, this))
  }
  initBrakeMaxVDEPRECATED(length: number): capnp.List<number> {
    return __S.initList(7, capnp.Float32List, length, this)
  }
  setBrakeMaxVDEPRECATED(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(7, this))
  }
  getDirectAccelControlDEPRECATED(): boolean {
    return __S.getBit(6, this)
  }
  setDirectAccelControlDEPRECATED(value: boolean): void {
    __S.setBit(6, value, this)
  }
  getMaxSteeringAngleDegDEPRECATED(): number {
    return __S.getFloat32(96, this)
  }
  setMaxSteeringAngleDegDEPRECATED(value: number): void {
    __S.setFloat32(96, value, this)
  }
  getLongitudinalActuatorDelayLowerBoundDEPRECATED(): number {
    return __S.getFloat32(112, this)
  }
  setLongitudinalActuatorDelayLowerBoundDEPRECATED(value: number): void {
    __S.setFloat32(112, value, this)
  }
  getStoppingControlDEPRECATED(): boolean {
    return __S.getBit(7, this)
  }
  setStoppingControlDEPRECATED(value: boolean): void {
    __S.setBit(7, value, this)
  }
  getRadarTimeStepDEPRECATED(): number {
    return __S.getFloat32(72, this, CarParams._capnp.defaultRadarTimeStepDEPRECATED)
  }
  setRadarTimeStepDEPRECATED(value: number): void {
    __S.setFloat32(72, value, this)
  }
  toString(): string {
    return 'CarParams_' + super.toString()
  }
}
CarState._ButtonEvents = capnp.CompositeList(CarState_ButtonEvent)
CarState._EventsDEPRECATED = capnp.CompositeList(OnroadEventDEPRECATED)
RadarData._Points = capnp.CompositeList(RadarData_RadarPoint)
CarParams._SafetyConfigs = capnp.CompositeList(CarParams_SafetyConfig)
CarParams._CarFw = capnp.CompositeList(CarParams_CarFw)
