/* tslint:disable */

/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */

import * as capnp from 'capnp-ts'
import { ObjectSize as __O, Struct as __S } from 'capnp-ts'
export const _capnpFileId = 'b526ba661d550a59'
export class CustomReserved0 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved0', id: '81c2f05a394cf4af', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved0_' + super.toString()
  }
}
export class CustomReserved1 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved1', id: 'aedffd8f31e7b55d', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved1_' + super.toString()
  }
}
export class CustomReserved2 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved2', id: 'f35cc4560bbf6ec2', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved2_' + super.toString()
  }
}
export class CustomReserved3 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved3', id: 'da96579883444c35', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved3_' + super.toString()
  }
}
export class CustomReserved4 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved4', id: '80ae746ee2596b11', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved4_' + super.toString()
  }
}
export class CustomReserved5 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved5', id: 'a5cd762cd951a455', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved5_' + super.toString()
  }
}
export class CustomReserved6 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved6', id: 'f98d843bfd7004a3', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved6_' + super.toString()
  }
}
export class CustomReserved7 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved7', id: 'b86e6369214c01c8', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved7_' + super.toString()
  }
}
export class CustomReserved8 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved8', id: 'f416ec09499d9d19', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved8_' + super.toString()
  }
}
export class CustomReserved9 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved9', id: 'a1680744031fdb2d', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved9_' + super.toString()
  }
}
export class CustomReserved10 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved10', id: 'cb9fd56c7057593a', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved10_' + super.toString()
  }
}
export class CustomReserved11 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved11', id: 'c2243c65e0340384', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved11_' + super.toString()
  }
}
export class CustomReserved12 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved12', id: '9ccdc8676701b412', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved12_' + super.toString()
  }
}
export class CustomReserved13 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved13', id: 'cd96dafb67a082d0', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved13_' + super.toString()
  }
}
export class CustomReserved14 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved14', id: 'b057204d7deadf3f', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved14_' + super.toString()
  }
}
export class CustomReserved15 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved15', id: 'bd443b539493bc68', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved15_' + super.toString()
  }
}
export class CustomReserved16 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved16', id: 'fc6241ed8877b611', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved16_' + super.toString()
  }
}
export class CustomReserved17 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved17', id: 'a30662f84033036c', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved17_' + super.toString()
  }
}
export class CustomReserved18 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved18', id: 'c86a3d38d13eb3ef', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved18_' + super.toString()
  }
}
export class CustomReserved19 extends __S {
  static readonly _capnp = { displayName: 'CustomReserved19', id: 'a4f1eb3323f5f582', size: new __O(0, 0) }
  toString(): string {
    return 'CustomReserved19_' + super.toString()
  }
}
