/* tslint:disable */

/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */

import * as capnp from 'capnp-ts'
import { ObjectSize as __O, Struct as __S } from 'capnp-ts'
export const _capnpFileId = '80ef1ec4889c2a63'
export class LogRotate extends __S {
  static readonly _capnp = { displayName: 'LogRotate', id: '9811e1f38f62f2d1', size: new __O(8, 1) }
  getSegmentNum(): number {
    return __S.getInt32(0, this)
  }
  setSegmentNum(value: number): void {
    __S.setInt32(0, value, this)
  }
  getPath(): string {
    return __S.getText(0, this)
  }
  setPath(value: string): void {
    __S.setText(0, value, this)
  }
  toString(): string {
    return 'LogRotate_' + super.toString()
  }
}
export class LiveUI extends __S {
  static readonly _capnp = { displayName: 'LiveUI', id: 'c08240f996aefced', size: new __O(8, 2) }
  getRearViewCam(): boolean {
    return __S.getBit(0, this)
  }
  setRearViewCam(value: boolean): void {
    __S.setBit(0, value, this)
  }
  getAlertText1(): string {
    return __S.getText(0, this)
  }
  setAlertText1(value: string): void {
    __S.setText(0, value, this)
  }
  getAlertText2(): string {
    return __S.getText(1, this)
  }
  setAlertText2(value: string): void {
    __S.setText(1, value, this)
  }
  getAwarenessStatus(): number {
    return __S.getFloat32(4, this)
  }
  setAwarenessStatus(value: number): void {
    __S.setFloat32(4, value, this)
  }
  toString(): string {
    return 'LiveUI_' + super.toString()
  }
}
export enum UiLayoutState_App {
  HOME,
  MUSIC,
  NAV,
  SETTINGS,
  NONE,
}
export class UiLayoutState extends __S {
  static readonly App = UiLayoutState_App
  static readonly _capnp = { displayName: 'UiLayoutState', id: '88dcce08ad29dda0', size: new __O(8, 0) }
  getActiveApp(): UiLayoutState_App {
    return __S.getUint16(0, this)
  }
  setActiveApp(value: UiLayoutState_App): void {
    __S.setUint16(0, value, this)
  }
  getSidebarCollapsed(): boolean {
    return __S.getBit(16, this)
  }
  setSidebarCollapsed(value: boolean): void {
    __S.setBit(16, value, this)
  }
  getMapEnabled(): boolean {
    return __S.getBit(17, this)
  }
  setMapEnabled(value: boolean): void {
    __S.setBit(17, value, this)
  }
  getMockEngaged(): boolean {
    return __S.getBit(18, this)
  }
  setMockEngaged(value: boolean): void {
    __S.setBit(18, value, this)
  }
  toString(): string {
    return 'UiLayoutState_' + super.toString()
  }
}
export class OrbslamCorrection extends __S {
  static readonly _capnp = { displayName: 'OrbslamCorrection', id: '8afd33dc9b35e1aa', size: new __O(16, 4) }
  getCorrectionMonoTime(): capnp.Uint64 {
    return __S.getUint64(0, this)
  }
  setCorrectionMonoTime(value: capnp.Uint64): void {
    __S.setUint64(0, value, this)
  }
  adoptPrePositionECEF(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownPrePositionECEF(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getPrePositionECEF())
  }
  getPrePositionECEF(): capnp.List<number> {
    return __S.getList(0, capnp.Float64List, this)
  }
  hasPrePositionECEF(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initPrePositionECEF(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float64List, length, this)
  }
  setPrePositionECEF(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptPostPositionECEF(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownPostPositionECEF(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getPostPositionECEF())
  }
  getPostPositionECEF(): capnp.List<number> {
    return __S.getList(1, capnp.Float64List, this)
  }
  hasPostPositionECEF(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initPostPositionECEF(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Float64List, length, this)
  }
  setPostPositionECEF(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  adoptPrePoseQuatECEF(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownPrePoseQuatECEF(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getPrePoseQuatECEF())
  }
  getPrePoseQuatECEF(): capnp.List<number> {
    return __S.getList(2, capnp.Float32List, this)
  }
  hasPrePoseQuatECEF(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initPrePoseQuatECEF(length: number): capnp.List<number> {
    return __S.initList(2, capnp.Float32List, length, this)
  }
  setPrePoseQuatECEF(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  adoptPostPoseQuatECEF(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(3, this))
  }
  disownPostPoseQuatECEF(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getPostPoseQuatECEF())
  }
  getPostPoseQuatECEF(): capnp.List<number> {
    return __S.getList(3, capnp.Float32List, this)
  }
  hasPostPoseQuatECEF(): boolean {
    return !__S.isNull(__S.getPointer(3, this))
  }
  initPostPoseQuatECEF(length: number): capnp.List<number> {
    return __S.initList(3, capnp.Float32List, length, this)
  }
  setPostPoseQuatECEF(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(3, this))
  }
  getNumInliers(): number {
    return __S.getUint32(8, this)
  }
  setNumInliers(value: number): void {
    __S.setUint32(8, value, this)
  }
  toString(): string {
    return 'OrbslamCorrection_' + super.toString()
  }
}
export class EthernetPacket extends __S {
  static readonly _capnp = { displayName: 'EthernetPacket', id: 'a99a9d5b33cf5859', size: new __O(8, 1) }
  adoptPkt(value: capnp.Orphan<capnp.Data>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownPkt(): capnp.Orphan<capnp.Data> {
    return __S.disown(this.getPkt())
  }
  getPkt(): capnp.Data {
    return __S.getData(0, this)
  }
  hasPkt(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initPkt(length: number): capnp.Data {
    return __S.initData(0, length, this)
  }
  setPkt(value: capnp.Data): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  getTs(): number {
    return __S.getFloat32(0, this)
  }
  setTs(value: number): void {
    __S.setFloat32(0, value, this)
  }
  toString(): string {
    return 'EthernetPacket_' + super.toString()
  }
}
export class CellInfo extends __S {
  static readonly _capnp = { displayName: 'CellInfo', id: 'cff7566681c277ce', size: new __O(8, 1) }
  getTimestamp(): capnp.Uint64 {
    return __S.getUint64(0, this)
  }
  setTimestamp(value: capnp.Uint64): void {
    __S.setUint64(0, value, this)
  }
  getRepr(): string {
    return __S.getText(0, this)
  }
  setRepr(value: string): void {
    __S.setText(0, value, this)
  }
  toString(): string {
    return 'CellInfo_' + super.toString()
  }
}
export enum WifiScan_ChannelWidth {
  W20MHZ,
  W40MHZ,
  W80MHZ,
  W160MHZ,
  W80PLUS80MHZ,
}
export class WifiScan extends __S {
  static readonly ChannelWidth = WifiScan_ChannelWidth
  static readonly _capnp = { displayName: 'WifiScan', id: 'd4df5a192382ba0b', size: new __O(40, 5) }
  getBssid(): string {
    return __S.getText(0, this)
  }
  setBssid(value: string): void {
    __S.setText(0, value, this)
  }
  getSsid(): string {
    return __S.getText(1, this)
  }
  setSsid(value: string): void {
    __S.setText(1, value, this)
  }
  getCapabilities(): string {
    return __S.getText(2, this)
  }
  setCapabilities(value: string): void {
    __S.setText(2, value, this)
  }
  getFrequency(): number {
    return __S.getInt32(0, this)
  }
  setFrequency(value: number): void {
    __S.setInt32(0, value, this)
  }
  getLevel(): number {
    return __S.getInt32(4, this)
  }
  setLevel(value: number): void {
    __S.setInt32(4, value, this)
  }
  getTimestamp(): capnp.Int64 {
    return __S.getInt64(8, this)
  }
  setTimestamp(value: capnp.Int64): void {
    __S.setInt64(8, value, this)
  }
  getCenterFreq0(): number {
    return __S.getInt32(16, this)
  }
  setCenterFreq0(value: number): void {
    __S.setInt32(16, value, this)
  }
  getCenterFreq1(): number {
    return __S.getInt32(20, this)
  }
  setCenterFreq1(value: number): void {
    __S.setInt32(20, value, this)
  }
  getChannelWidth(): WifiScan_ChannelWidth {
    return __S.getUint16(24, this)
  }
  setChannelWidth(value: WifiScan_ChannelWidth): void {
    __S.setUint16(24, value, this)
  }
  getOperatorFriendlyName(): string {
    return __S.getText(3, this)
  }
  setOperatorFriendlyName(value: string): void {
    __S.setText(3, value, this)
  }
  getVenueName(): string {
    return __S.getText(4, this)
  }
  setVenueName(value: string): void {
    __S.setText(4, value, this)
  }
  getIs80211mcResponder(): boolean {
    return __S.getBit(208, this)
  }
  setIs80211mcResponder(value: boolean): void {
    __S.setBit(208, value, this)
  }
  getPasspoint(): boolean {
    return __S.getBit(209, this)
  }
  setPasspoint(value: boolean): void {
    __S.setBit(209, value, this)
  }
  getDistanceCm(): number {
    return __S.getInt32(28, this)
  }
  setDistanceCm(value: number): void {
    __S.setInt32(28, value, this)
  }
  getDistanceSdCm(): number {
    return __S.getInt32(32, this)
  }
  setDistanceSdCm(value: number): void {
    __S.setInt32(32, value, this)
  }
  toString(): string {
    return 'WifiScan_' + super.toString()
  }
}
export class LiveEventData extends __S {
  static readonly _capnp = { displayName: 'LiveEventData', id: '94b7baa90c5c321e', size: new __O(8, 1) }
  getName(): string {
    return __S.getText(0, this)
  }
  setName(value: string): void {
    __S.setText(0, value, this)
  }
  getValue(): number {
    return __S.getInt32(0, this)
  }
  setValue(value: number): void {
    __S.setInt32(0, value, this)
  }
  toString(): string {
    return 'LiveEventData_' + super.toString()
  }
}
export class ModelData_PathData extends __S {
  static readonly _capnp = { displayName: 'PathData', id: '8817eeea389e9f08', size: new __O(16, 3) }
  adoptPoints(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownPoints(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getPoints())
  }
  getPoints(): capnp.List<number> {
    return __S.getList(0, capnp.Float32List, this)
  }
  hasPoints(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initPoints(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float32List, length, this)
  }
  setPoints(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  getProb(): number {
    return __S.getFloat32(0, this)
  }
  setProb(value: number): void {
    __S.setFloat32(0, value, this)
  }
  getStd(): number {
    return __S.getFloat32(4, this)
  }
  setStd(value: number): void {
    __S.setFloat32(4, value, this)
  }
  adoptStds(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownStds(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getStds())
  }
  getStds(): capnp.List<number> {
    return __S.getList(1, capnp.Float32List, this)
  }
  hasStds(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initStds(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Float32List, length, this)
  }
  setStds(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  adoptPoly(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownPoly(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getPoly())
  }
  getPoly(): capnp.List<number> {
    return __S.getList(2, capnp.Float32List, this)
  }
  hasPoly(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initPoly(length: number): capnp.List<number> {
    return __S.initList(2, capnp.Float32List, length, this)
  }
  setPoly(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  getValidLen(): number {
    return __S.getFloat32(8, this)
  }
  setValidLen(value: number): void {
    __S.setFloat32(8, value, this)
  }
  toString(): string {
    return 'ModelData_PathData_' + super.toString()
  }
}
export class ModelData_LeadData extends __S {
  static readonly _capnp = { displayName: 'LeadData', id: 'd1c9bef96d26fa91', size: new __O(40, 0) }
  getDist(): number {
    return __S.getFloat32(0, this)
  }
  setDist(value: number): void {
    __S.setFloat32(0, value, this)
  }
  getProb(): number {
    return __S.getFloat32(4, this)
  }
  setProb(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getStd(): number {
    return __S.getFloat32(8, this)
  }
  setStd(value: number): void {
    __S.setFloat32(8, value, this)
  }
  getRelVel(): number {
    return __S.getFloat32(12, this)
  }
  setRelVel(value: number): void {
    __S.setFloat32(12, value, this)
  }
  getRelVelStd(): number {
    return __S.getFloat32(16, this)
  }
  setRelVelStd(value: number): void {
    __S.setFloat32(16, value, this)
  }
  getRelY(): number {
    return __S.getFloat32(20, this)
  }
  setRelY(value: number): void {
    __S.setFloat32(20, value, this)
  }
  getRelYStd(): number {
    return __S.getFloat32(24, this)
  }
  setRelYStd(value: number): void {
    __S.setFloat32(24, value, this)
  }
  getRelA(): number {
    return __S.getFloat32(28, this)
  }
  setRelA(value: number): void {
    __S.setFloat32(28, value, this)
  }
  getRelAStd(): number {
    return __S.getFloat32(32, this)
  }
  setRelAStd(value: number): void {
    __S.setFloat32(32, value, this)
  }
  toString(): string {
    return 'ModelData_LeadData_' + super.toString()
  }
}
export class ModelData_ModelSettings extends __S {
  static readonly _capnp = { displayName: 'ModelSettings', id: 'a26e3710efd3e914', size: new __O(8, 3) }
  getBigBoxX(): number {
    return __S.getUint16(0, this)
  }
  setBigBoxX(value: number): void {
    __S.setUint16(0, value, this)
  }
  getBigBoxY(): number {
    return __S.getUint16(2, this)
  }
  setBigBoxY(value: number): void {
    __S.setUint16(2, value, this)
  }
  getBigBoxWidth(): number {
    return __S.getUint16(4, this)
  }
  setBigBoxWidth(value: number): void {
    __S.setUint16(4, value, this)
  }
  getBigBoxHeight(): number {
    return __S.getUint16(6, this)
  }
  setBigBoxHeight(value: number): void {
    __S.setUint16(6, value, this)
  }
  adoptBoxProjection(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownBoxProjection(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getBoxProjection())
  }
  getBoxProjection(): capnp.List<number> {
    return __S.getList(0, capnp.Float32List, this)
  }
  hasBoxProjection(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initBoxProjection(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float32List, length, this)
  }
  setBoxProjection(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptYuvCorrection(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownYuvCorrection(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getYuvCorrection())
  }
  getYuvCorrection(): capnp.List<number> {
    return __S.getList(1, capnp.Float32List, this)
  }
  hasYuvCorrection(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initYuvCorrection(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Float32List, length, this)
  }
  setYuvCorrection(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  adoptInputTransform(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownInputTransform(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getInputTransform())
  }
  getInputTransform(): capnp.List<number> {
    return __S.getList(2, capnp.Float32List, this)
  }
  hasInputTransform(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initInputTransform(length: number): capnp.List<number> {
    return __S.initList(2, capnp.Float32List, length, this)
  }
  setInputTransform(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  toString(): string {
    return 'ModelData_ModelSettings_' + super.toString()
  }
}
export class ModelData_MetaData extends __S {
  static readonly _capnp = { displayName: 'MetaData', id: '9744f25fb60f2bf8', size: new __O(16, 2) }
  getEngagedProb(): number {
    return __S.getFloat32(0, this)
  }
  setEngagedProb(value: number): void {
    __S.setFloat32(0, value, this)
  }
  adoptDesirePrediction(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownDesirePrediction(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getDesirePrediction())
  }
  getDesirePrediction(): capnp.List<number> {
    return __S.getList(0, capnp.Float32List, this)
  }
  hasDesirePrediction(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initDesirePrediction(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float32List, length, this)
  }
  setDesirePrediction(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  getBrakeDisengageProb(): number {
    return __S.getFloat32(4, this)
  }
  setBrakeDisengageProb(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getGasDisengageProb(): number {
    return __S.getFloat32(8, this)
  }
  setGasDisengageProb(value: number): void {
    __S.setFloat32(8, value, this)
  }
  getSteerOverrideProb(): number {
    return __S.getFloat32(12, this)
  }
  setSteerOverrideProb(value: number): void {
    __S.setFloat32(12, value, this)
  }
  adoptDesireState(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownDesireState(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getDesireState())
  }
  getDesireState(): capnp.List<number> {
    return __S.getList(1, capnp.Float32List, this)
  }
  hasDesireState(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initDesireState(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Float32List, length, this)
  }
  setDesireState(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  toString(): string {
    return 'ModelData_MetaData_' + super.toString()
  }
}
export class ModelData_LongitudinalData extends __S {
  static readonly _capnp = { displayName: 'LongitudinalData', id: 'f98f999c6a071122', size: new __O(0, 3) }
  adoptDistances(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownDistances(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getDistances())
  }
  getDistances(): capnp.List<number> {
    return __S.getList(2, capnp.Float32List, this)
  }
  hasDistances(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initDistances(length: number): capnp.List<number> {
    return __S.initList(2, capnp.Float32List, length, this)
  }
  setDistances(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  adoptSpeeds(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownSpeeds(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getSpeeds())
  }
  getSpeeds(): capnp.List<number> {
    return __S.getList(0, capnp.Float32List, this)
  }
  hasSpeeds(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initSpeeds(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float32List, length, this)
  }
  setSpeeds(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptAccelerations(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownAccelerations(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getAccelerations())
  }
  getAccelerations(): capnp.List<number> {
    return __S.getList(1, capnp.Float32List, this)
  }
  hasAccelerations(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initAccelerations(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Float32List, length, this)
  }
  setAccelerations(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  toString(): string {
    return 'ModelData_LongitudinalData_' + super.toString()
  }
}
export class ModelData extends __S {
  static readonly PathData = ModelData_PathData
  static readonly LeadData = ModelData_LeadData
  static readonly ModelSettings = ModelData_ModelSettings
  static readonly MetaData = ModelData_MetaData
  static readonly LongitudinalData = ModelData_LongitudinalData
  static readonly _capnp = { displayName: 'ModelData', id: 'b8aad62cffef28a9', size: new __O(32, 11) }
  getFrameId(): number {
    return __S.getUint32(0, this)
  }
  setFrameId(value: number): void {
    __S.setUint32(0, value, this)
  }
  getFrameAge(): number {
    return __S.getUint32(4, this)
  }
  setFrameAge(value: number): void {
    __S.setUint32(4, value, this)
  }
  getFrameDropPerc(): number {
    return __S.getFloat32(16, this)
  }
  setFrameDropPerc(value: number): void {
    __S.setFloat32(16, value, this)
  }
  getTimestampEof(): capnp.Uint64 {
    return __S.getUint64(8, this)
  }
  setTimestampEof(value: capnp.Uint64): void {
    __S.setUint64(8, value, this)
  }
  getModelExecutionTime(): number {
    return __S.getFloat32(20, this)
  }
  setModelExecutionTime(value: number): void {
    __S.setFloat32(20, value, this)
  }
  getGpuExecutionTime(): number {
    return __S.getFloat32(24, this)
  }
  setGpuExecutionTime(value: number): void {
    __S.setFloat32(24, value, this)
  }
  adoptRawPred(value: capnp.Orphan<capnp.Data>): void {
    __S.adopt(value, __S.getPointer(10, this))
  }
  disownRawPred(): capnp.Orphan<capnp.Data> {
    return __S.disown(this.getRawPred())
  }
  getRawPred(): capnp.Data {
    return __S.getData(10, this)
  }
  hasRawPred(): boolean {
    return !__S.isNull(__S.getPointer(10, this))
  }
  initRawPred(length: number): capnp.Data {
    return __S.initData(10, length, this)
  }
  setRawPred(value: capnp.Data): void {
    __S.copyFrom(value, __S.getPointer(10, this))
  }
  adoptPath(value: capnp.Orphan<ModelData_PathData>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownPath(): capnp.Orphan<ModelData_PathData> {
    return __S.disown(this.getPath())
  }
  getPath(): ModelData_PathData {
    return __S.getStruct(0, ModelData_PathData, this)
  }
  hasPath(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initPath(): ModelData_PathData {
    return __S.initStructAt(0, ModelData_PathData, this)
  }
  setPath(value: ModelData_PathData): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptLeftLane(value: capnp.Orphan<ModelData_PathData>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownLeftLane(): capnp.Orphan<ModelData_PathData> {
    return __S.disown(this.getLeftLane())
  }
  getLeftLane(): ModelData_PathData {
    return __S.getStruct(1, ModelData_PathData, this)
  }
  hasLeftLane(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initLeftLane(): ModelData_PathData {
    return __S.initStructAt(1, ModelData_PathData, this)
  }
  setLeftLane(value: ModelData_PathData): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  adoptRightLane(value: capnp.Orphan<ModelData_PathData>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownRightLane(): capnp.Orphan<ModelData_PathData> {
    return __S.disown(this.getRightLane())
  }
  getRightLane(): ModelData_PathData {
    return __S.getStruct(2, ModelData_PathData, this)
  }
  hasRightLane(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initRightLane(): ModelData_PathData {
    return __S.initStructAt(2, ModelData_PathData, this)
  }
  setRightLane(value: ModelData_PathData): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  adoptLead(value: capnp.Orphan<ModelData_LeadData>): void {
    __S.adopt(value, __S.getPointer(3, this))
  }
  disownLead(): capnp.Orphan<ModelData_LeadData> {
    return __S.disown(this.getLead())
  }
  getLead(): ModelData_LeadData {
    return __S.getStruct(3, ModelData_LeadData, this)
  }
  hasLead(): boolean {
    return !__S.isNull(__S.getPointer(3, this))
  }
  initLead(): ModelData_LeadData {
    return __S.initStructAt(3, ModelData_LeadData, this)
  }
  setLead(value: ModelData_LeadData): void {
    __S.copyFrom(value, __S.getPointer(3, this))
  }
  adoptFreePath(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(5, this))
  }
  disownFreePath(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getFreePath())
  }
  getFreePath(): capnp.List<number> {
    return __S.getList(5, capnp.Float32List, this)
  }
  hasFreePath(): boolean {
    return !__S.isNull(__S.getPointer(5, this))
  }
  initFreePath(length: number): capnp.List<number> {
    return __S.initList(5, capnp.Float32List, length, this)
  }
  setFreePath(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(5, this))
  }
  adoptSettings(value: capnp.Orphan<ModelData_ModelSettings>): void {
    __S.adopt(value, __S.getPointer(4, this))
  }
  disownSettings(): capnp.Orphan<ModelData_ModelSettings> {
    return __S.disown(this.getSettings())
  }
  getSettings(): ModelData_ModelSettings {
    return __S.getStruct(4, ModelData_ModelSettings, this)
  }
  hasSettings(): boolean {
    return !__S.isNull(__S.getPointer(4, this))
  }
  initSettings(): ModelData_ModelSettings {
    return __S.initStructAt(4, ModelData_ModelSettings, this)
  }
  setSettings(value: ModelData_ModelSettings): void {
    __S.copyFrom(value, __S.getPointer(4, this))
  }
  adoptLeadFuture(value: capnp.Orphan<ModelData_LeadData>): void {
    __S.adopt(value, __S.getPointer(6, this))
  }
  disownLeadFuture(): capnp.Orphan<ModelData_LeadData> {
    return __S.disown(this.getLeadFuture())
  }
  getLeadFuture(): ModelData_LeadData {
    return __S.getStruct(6, ModelData_LeadData, this)
  }
  hasLeadFuture(): boolean {
    return !__S.isNull(__S.getPointer(6, this))
  }
  initLeadFuture(): ModelData_LeadData {
    return __S.initStructAt(6, ModelData_LeadData, this)
  }
  setLeadFuture(value: ModelData_LeadData): void {
    __S.copyFrom(value, __S.getPointer(6, this))
  }
  adoptSpeed(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(7, this))
  }
  disownSpeed(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getSpeed())
  }
  getSpeed(): capnp.List<number> {
    return __S.getList(7, capnp.Float32List, this)
  }
  hasSpeed(): boolean {
    return !__S.isNull(__S.getPointer(7, this))
  }
  initSpeed(length: number): capnp.List<number> {
    return __S.initList(7, capnp.Float32List, length, this)
  }
  setSpeed(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(7, this))
  }
  adoptMeta(value: capnp.Orphan<ModelData_MetaData>): void {
    __S.adopt(value, __S.getPointer(8, this))
  }
  disownMeta(): capnp.Orphan<ModelData_MetaData> {
    return __S.disown(this.getMeta())
  }
  getMeta(): ModelData_MetaData {
    return __S.getStruct(8, ModelData_MetaData, this)
  }
  hasMeta(): boolean {
    return !__S.isNull(__S.getPointer(8, this))
  }
  initMeta(): ModelData_MetaData {
    return __S.initStructAt(8, ModelData_MetaData, this)
  }
  setMeta(value: ModelData_MetaData): void {
    __S.copyFrom(value, __S.getPointer(8, this))
  }
  adoptLongitudinal(value: capnp.Orphan<ModelData_LongitudinalData>): void {
    __S.adopt(value, __S.getPointer(9, this))
  }
  disownLongitudinal(): capnp.Orphan<ModelData_LongitudinalData> {
    return __S.disown(this.getLongitudinal())
  }
  getLongitudinal(): ModelData_LongitudinalData {
    return __S.getStruct(9, ModelData_LongitudinalData, this)
  }
  hasLongitudinal(): boolean {
    return !__S.isNull(__S.getPointer(9, this))
  }
  initLongitudinal(): ModelData_LongitudinalData {
    return __S.initStructAt(9, ModelData_LongitudinalData, this)
  }
  setLongitudinal(value: ModelData_LongitudinalData): void {
    __S.copyFrom(value, __S.getPointer(9, this))
  }
  toString(): string {
    return 'ModelData_' + super.toString()
  }
}
export class ECEFPoint extends __S {
  static readonly _capnp = { displayName: 'ECEFPoint', id: 'c25bbbd524983447', size: new __O(24, 0) }
  getX(): number {
    return __S.getFloat64(0, this)
  }
  setX(value: number): void {
    __S.setFloat64(0, value, this)
  }
  getY(): number {
    return __S.getFloat64(8, this)
  }
  setY(value: number): void {
    __S.setFloat64(8, value, this)
  }
  getZ(): number {
    return __S.getFloat64(16, this)
  }
  setZ(value: number): void {
    __S.setFloat64(16, value, this)
  }
  toString(): string {
    return 'ECEFPoint_' + super.toString()
  }
}
export class ECEFPointDEPRECATED extends __S {
  static readonly _capnp = { displayName: 'ECEFPointDEPRECATED', id: 'e10e21168db0c7f7', size: new __O(16, 0) }
  getX(): number {
    return __S.getFloat32(0, this)
  }
  setX(value: number): void {
    __S.setFloat32(0, value, this)
  }
  getY(): number {
    return __S.getFloat32(4, this)
  }
  setY(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getZ(): number {
    return __S.getFloat32(8, this)
  }
  setZ(value: number): void {
    __S.setFloat32(8, value, this)
  }
  toString(): string {
    return 'ECEFPointDEPRECATED_' + super.toString()
  }
}
export class GPSPlannerPoints extends __S {
  static readonly _capnp = { displayName: 'GPSPlannerPoints', id: 'ab54c59699f8f9f3', size: new __O(16, 5) }
  static _PointsDEPRECATED: capnp.ListCtor<ECEFPointDEPRECATED>
  static _Points: capnp.ListCtor<ECEFPoint>
  adoptCurPosDEPRECATED(value: capnp.Orphan<ECEFPointDEPRECATED>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownCurPosDEPRECATED(): capnp.Orphan<ECEFPointDEPRECATED> {
    return __S.disown(this.getCurPosDEPRECATED())
  }
  getCurPosDEPRECATED(): ECEFPointDEPRECATED {
    return __S.getStruct(0, ECEFPointDEPRECATED, this)
  }
  hasCurPosDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initCurPosDEPRECATED(): ECEFPointDEPRECATED {
    return __S.initStructAt(0, ECEFPointDEPRECATED, this)
  }
  setCurPosDEPRECATED(value: ECEFPointDEPRECATED): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptPointsDEPRECATED(value: capnp.Orphan<capnp.List<ECEFPointDEPRECATED>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownPointsDEPRECATED(): capnp.Orphan<capnp.List<ECEFPointDEPRECATED>> {
    return __S.disown(this.getPointsDEPRECATED())
  }
  getPointsDEPRECATED(): capnp.List<ECEFPointDEPRECATED> {
    return __S.getList(1, GPSPlannerPoints._PointsDEPRECATED, this)
  }
  hasPointsDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initPointsDEPRECATED(length: number): capnp.List<ECEFPointDEPRECATED> {
    return __S.initList(1, GPSPlannerPoints._PointsDEPRECATED, length, this)
  }
  setPointsDEPRECATED(value: capnp.List<ECEFPointDEPRECATED>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  adoptCurPos(value: capnp.Orphan<ECEFPoint>): void {
    __S.adopt(value, __S.getPointer(3, this))
  }
  disownCurPos(): capnp.Orphan<ECEFPoint> {
    return __S.disown(this.getCurPos())
  }
  getCurPos(): ECEFPoint {
    return __S.getStruct(3, ECEFPoint, this)
  }
  hasCurPos(): boolean {
    return !__S.isNull(__S.getPointer(3, this))
  }
  initCurPos(): ECEFPoint {
    return __S.initStructAt(3, ECEFPoint, this)
  }
  setCurPos(value: ECEFPoint): void {
    __S.copyFrom(value, __S.getPointer(3, this))
  }
  adoptPoints(value: capnp.Orphan<capnp.List<ECEFPoint>>): void {
    __S.adopt(value, __S.getPointer(4, this))
  }
  disownPoints(): capnp.Orphan<capnp.List<ECEFPoint>> {
    return __S.disown(this.getPoints())
  }
  getPoints(): capnp.List<ECEFPoint> {
    return __S.getList(4, GPSPlannerPoints._Points, this)
  }
  hasPoints(): boolean {
    return !__S.isNull(__S.getPointer(4, this))
  }
  initPoints(length: number): capnp.List<ECEFPoint> {
    return __S.initList(4, GPSPlannerPoints._Points, length, this)
  }
  setPoints(value: capnp.List<ECEFPoint>): void {
    __S.copyFrom(value, __S.getPointer(4, this))
  }
  getValid(): boolean {
    return __S.getBit(0, this)
  }
  setValid(value: boolean): void {
    __S.setBit(0, value, this)
  }
  getTrackName(): string {
    return __S.getText(2, this)
  }
  setTrackName(value: string): void {
    __S.setText(2, value, this)
  }
  getSpeedLimit(): number {
    return __S.getFloat32(4, this)
  }
  setSpeedLimit(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getAccelTarget(): number {
    return __S.getFloat32(8, this)
  }
  setAccelTarget(value: number): void {
    __S.setFloat32(8, value, this)
  }
  toString(): string {
    return 'GPSPlannerPoints_' + super.toString()
  }
}
export class GPSPlannerPlan extends __S {
  static readonly _capnp = { displayName: 'GPSPlannerPlan', id: 'f5ad1d90cdc1dd6b', size: new __O(16, 4) }
  static _PointsDEPRECATED: capnp.ListCtor<ECEFPointDEPRECATED>
  static _Points: capnp.ListCtor<ECEFPoint>
  getValid(): boolean {
    return __S.getBit(0, this)
  }
  setValid(value: boolean): void {
    __S.setBit(0, value, this)
  }
  adoptPoly(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownPoly(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getPoly())
  }
  getPoly(): capnp.List<number> {
    return __S.getList(0, capnp.Float32List, this)
  }
  hasPoly(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initPoly(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float32List, length, this)
  }
  setPoly(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  getTrackName(): string {
    return __S.getText(1, this)
  }
  setTrackName(value: string): void {
    __S.setText(1, value, this)
  }
  getSpeed(): number {
    return __S.getFloat32(4, this)
  }
  setSpeed(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getAcceleration(): number {
    return __S.getFloat32(8, this)
  }
  setAcceleration(value: number): void {
    __S.setFloat32(8, value, this)
  }
  adoptPointsDEPRECATED(value: capnp.Orphan<capnp.List<ECEFPointDEPRECATED>>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownPointsDEPRECATED(): capnp.Orphan<capnp.List<ECEFPointDEPRECATED>> {
    return __S.disown(this.getPointsDEPRECATED())
  }
  getPointsDEPRECATED(): capnp.List<ECEFPointDEPRECATED> {
    return __S.getList(2, GPSPlannerPlan._PointsDEPRECATED, this)
  }
  hasPointsDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initPointsDEPRECATED(length: number): capnp.List<ECEFPointDEPRECATED> {
    return __S.initList(2, GPSPlannerPlan._PointsDEPRECATED, length, this)
  }
  setPointsDEPRECATED(value: capnp.List<ECEFPointDEPRECATED>): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  adoptPoints(value: capnp.Orphan<capnp.List<ECEFPoint>>): void {
    __S.adopt(value, __S.getPointer(3, this))
  }
  disownPoints(): capnp.Orphan<capnp.List<ECEFPoint>> {
    return __S.disown(this.getPoints())
  }
  getPoints(): capnp.List<ECEFPoint> {
    return __S.getList(3, GPSPlannerPlan._Points, this)
  }
  hasPoints(): boolean {
    return !__S.isNull(__S.getPointer(3, this))
  }
  initPoints(length: number): capnp.List<ECEFPoint> {
    return __S.initList(3, GPSPlannerPlan._Points, length, this)
  }
  setPoints(value: capnp.List<ECEFPoint>): void {
    __S.copyFrom(value, __S.getPointer(3, this))
  }
  getXLookahead(): number {
    return __S.getFloat32(12, this)
  }
  setXLookahead(value: number): void {
    __S.setFloat32(12, value, this)
  }
  toString(): string {
    return 'GPSPlannerPlan_' + super.toString()
  }
}
export enum UiNavigationEvent_Type {
  NONE,
  LANE_CHANGE_LEFT,
  LANE_CHANGE_RIGHT,
  MERGE_LEFT,
  MERGE_RIGHT,
  TURN_LEFT,
  TURN_RIGHT,
}
export enum UiNavigationEvent_Status {
  NONE,
  PASSIVE,
  APPROACHING,
  ACTIVE,
}
export class UiNavigationEvent extends __S {
  static readonly Type = UiNavigationEvent_Type
  static readonly Status = UiNavigationEvent_Status
  static readonly _capnp = { displayName: 'UiNavigationEvent', id: '90c8426c3eaddd3b', size: new __O(8, 2) }
  getType(): UiNavigationEvent_Type {
    return __S.getUint16(0, this)
  }
  setType(value: UiNavigationEvent_Type): void {
    __S.setUint16(0, value, this)
  }
  getStatus(): UiNavigationEvent_Status {
    return __S.getUint16(2, this)
  }
  setStatus(value: UiNavigationEvent_Status): void {
    __S.setUint16(2, value, this)
  }
  getDistanceTo(): number {
    return __S.getFloat32(4, this)
  }
  setDistanceTo(value: number): void {
    __S.setFloat32(4, value, this)
  }
  adoptEndRoadPointDEPRECATED(value: capnp.Orphan<ECEFPointDEPRECATED>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownEndRoadPointDEPRECATED(): capnp.Orphan<ECEFPointDEPRECATED> {
    return __S.disown(this.getEndRoadPointDEPRECATED())
  }
  getEndRoadPointDEPRECATED(): ECEFPointDEPRECATED {
    return __S.getStruct(0, ECEFPointDEPRECATED, this)
  }
  hasEndRoadPointDEPRECATED(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initEndRoadPointDEPRECATED(): ECEFPointDEPRECATED {
    return __S.initStructAt(0, ECEFPointDEPRECATED, this)
  }
  setEndRoadPointDEPRECATED(value: ECEFPointDEPRECATED): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptEndRoadPoint(value: capnp.Orphan<ECEFPoint>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownEndRoadPoint(): capnp.Orphan<ECEFPoint> {
    return __S.disown(this.getEndRoadPoint())
  }
  getEndRoadPoint(): ECEFPoint {
    return __S.getStruct(1, ECEFPoint, this)
  }
  hasEndRoadPoint(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initEndRoadPoint(): ECEFPoint {
    return __S.initStructAt(1, ECEFPoint, this)
  }
  setEndRoadPoint(value: ECEFPoint): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  toString(): string {
    return 'UiNavigationEvent_' + super.toString()
  }
}
export class LiveLocationData_Accuracy extends __S {
  static readonly _capnp = { displayName: 'Accuracy', id: '943dc4625473b03f', size: new __O(24, 2) }
  adoptPNEDError(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownPNEDError(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getPNEDError())
  }
  getPNEDError(): capnp.List<number> {
    return __S.getList(0, capnp.Float32List, this)
  }
  hasPNEDError(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initPNEDError(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float32List, length, this)
  }
  setPNEDError(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptVNEDError(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownVNEDError(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getVNEDError())
  }
  getVNEDError(): capnp.List<number> {
    return __S.getList(1, capnp.Float32List, this)
  }
  hasVNEDError(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initVNEDError(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Float32List, length, this)
  }
  setVNEDError(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  getRollError(): number {
    return __S.getFloat32(0, this)
  }
  setRollError(value: number): void {
    __S.setFloat32(0, value, this)
  }
  getPitchError(): number {
    return __S.getFloat32(4, this)
  }
  setPitchError(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getHeadingError(): number {
    return __S.getFloat32(8, this)
  }
  setHeadingError(value: number): void {
    __S.setFloat32(8, value, this)
  }
  getEllipsoidSemiMajorError(): number {
    return __S.getFloat32(12, this)
  }
  setEllipsoidSemiMajorError(value: number): void {
    __S.setFloat32(12, value, this)
  }
  getEllipsoidSemiMinorError(): number {
    return __S.getFloat32(16, this)
  }
  setEllipsoidSemiMinorError(value: number): void {
    __S.setFloat32(16, value, this)
  }
  getEllipsoidOrientationError(): number {
    return __S.getFloat32(20, this)
  }
  setEllipsoidOrientationError(value: number): void {
    __S.setFloat32(20, value, this)
  }
  toString(): string {
    return 'LiveLocationData_Accuracy_' + super.toString()
  }
}
export enum LiveLocationData_SensorSource {
  APPLANIX,
  KALMAN,
  ORBSLAM,
  TIMING,
  DUMMY,
}
export class LiveLocationData extends __S {
  static readonly Accuracy = LiveLocationData_Accuracy
  static readonly SensorSource = LiveLocationData_SensorSource
  static readonly _capnp = { displayName: 'LiveLocationData', id: 'b99b2bc7a57e8128', size: new __O(80, 7) }
  getStatus(): number {
    return __S.getUint8(0, this)
  }
  setStatus(value: number): void {
    __S.setUint8(0, value, this)
  }
  getLat(): number {
    return __S.getFloat64(8, this)
  }
  setLat(value: number): void {
    __S.setFloat64(8, value, this)
  }
  getLon(): number {
    return __S.getFloat64(16, this)
  }
  setLon(value: number): void {
    __S.setFloat64(16, value, this)
  }
  getAlt(): number {
    return __S.getFloat32(4, this)
  }
  setAlt(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getSpeed(): number {
    return __S.getFloat32(24, this)
  }
  setSpeed(value: number): void {
    __S.setFloat32(24, value, this)
  }
  adoptVNED(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownVNED(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getVNED())
  }
  getVNED(): capnp.List<number> {
    return __S.getList(0, capnp.Float32List, this)
  }
  hasVNED(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initVNED(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float32List, length, this)
  }
  setVNED(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  getRoll(): number {
    return __S.getFloat32(28, this)
  }
  setRoll(value: number): void {
    __S.setFloat32(28, value, this)
  }
  getPitch(): number {
    return __S.getFloat32(32, this)
  }
  setPitch(value: number): void {
    __S.setFloat32(32, value, this)
  }
  getHeading(): number {
    return __S.getFloat32(36, this)
  }
  setHeading(value: number): void {
    __S.setFloat32(36, value, this)
  }
  getWanderAngle(): number {
    return __S.getFloat32(40, this)
  }
  setWanderAngle(value: number): void {
    __S.setFloat32(40, value, this)
  }
  getTrackAngle(): number {
    return __S.getFloat32(44, this)
  }
  setTrackAngle(value: number): void {
    __S.setFloat32(44, value, this)
  }
  adoptGyro(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownGyro(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getGyro())
  }
  getGyro(): capnp.List<number> {
    return __S.getList(1, capnp.Float32List, this)
  }
  hasGyro(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initGyro(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Float32List, length, this)
  }
  setGyro(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  adoptAccel(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownAccel(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getAccel())
  }
  getAccel(): capnp.List<number> {
    return __S.getList(2, capnp.Float32List, this)
  }
  hasAccel(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initAccel(length: number): capnp.List<number> {
    return __S.initList(2, capnp.Float32List, length, this)
  }
  setAccel(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  adoptAccuracy(value: capnp.Orphan<LiveLocationData_Accuracy>): void {
    __S.adopt(value, __S.getPointer(3, this))
  }
  disownAccuracy(): capnp.Orphan<LiveLocationData_Accuracy> {
    return __S.disown(this.getAccuracy())
  }
  getAccuracy(): LiveLocationData_Accuracy {
    return __S.getStruct(3, LiveLocationData_Accuracy, this)
  }
  hasAccuracy(): boolean {
    return !__S.isNull(__S.getPointer(3, this))
  }
  initAccuracy(): LiveLocationData_Accuracy {
    return __S.initStructAt(3, LiveLocationData_Accuracy, this)
  }
  setAccuracy(value: LiveLocationData_Accuracy): void {
    __S.copyFrom(value, __S.getPointer(3, this))
  }
  getSource(): LiveLocationData_SensorSource {
    return __S.getUint16(2, this)
  }
  setSource(value: LiveLocationData_SensorSource): void {
    __S.setUint16(2, value, this)
  }
  getFixMonoTime(): capnp.Uint64 {
    return __S.getUint64(48, this)
  }
  setFixMonoTime(value: capnp.Uint64): void {
    __S.setUint64(48, value, this)
  }
  getGpsWeek(): number {
    return __S.getInt32(56, this)
  }
  setGpsWeek(value: number): void {
    __S.setInt32(56, value, this)
  }
  getTimeOfWeek(): number {
    return __S.getFloat64(64, this)
  }
  setTimeOfWeek(value: number): void {
    __S.setFloat64(64, value, this)
  }
  adoptPositionECEF(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(4, this))
  }
  disownPositionECEF(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getPositionECEF())
  }
  getPositionECEF(): capnp.List<number> {
    return __S.getList(4, capnp.Float64List, this)
  }
  hasPositionECEF(): boolean {
    return !__S.isNull(__S.getPointer(4, this))
  }
  initPositionECEF(length: number): capnp.List<number> {
    return __S.initList(4, capnp.Float64List, length, this)
  }
  setPositionECEF(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(4, this))
  }
  adoptPoseQuatECEF(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(5, this))
  }
  disownPoseQuatECEF(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getPoseQuatECEF())
  }
  getPoseQuatECEF(): capnp.List<number> {
    return __S.getList(5, capnp.Float32List, this)
  }
  hasPoseQuatECEF(): boolean {
    return !__S.isNull(__S.getPointer(5, this))
  }
  initPoseQuatECEF(length: number): capnp.List<number> {
    return __S.initList(5, capnp.Float32List, length, this)
  }
  setPoseQuatECEF(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(5, this))
  }
  getPitchCalibration(): number {
    return __S.getFloat32(60, this)
  }
  setPitchCalibration(value: number): void {
    __S.setFloat32(60, value, this)
  }
  getYawCalibration(): number {
    return __S.getFloat32(72, this)
  }
  setYawCalibration(value: number): void {
    __S.setFloat32(72, value, this)
  }
  adoptImuFrame(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(6, this))
  }
  disownImuFrame(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getImuFrame())
  }
  getImuFrame(): capnp.List<number> {
    return __S.getList(6, capnp.Float32List, this)
  }
  hasImuFrame(): boolean {
    return !__S.isNull(__S.getPointer(6, this))
  }
  initImuFrame(length: number): capnp.List<number> {
    return __S.initList(6, capnp.Float32List, length, this)
  }
  setImuFrame(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(6, this))
  }
  toString(): string {
    return 'LiveLocationData_' + super.toString()
  }
}
export class OrbOdometry extends __S {
  static readonly _capnp = { displayName: 'OrbOdometry', id: 'd7700859ed1f5b76', size: new __O(32, 2) }
  getStartMonoTime(): capnp.Uint64 {
    return __S.getUint64(0, this)
  }
  setStartMonoTime(value: capnp.Uint64): void {
    __S.setUint64(0, value, this)
  }
  getEndMonoTime(): capnp.Uint64 {
    return __S.getUint64(8, this)
  }
  setEndMonoTime(value: capnp.Uint64): void {
    __S.setUint64(8, value, this)
  }
  adoptF(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownF(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getF())
  }
  getF(): capnp.List<number> {
    return __S.getList(0, capnp.Float64List, this)
  }
  hasF(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initF(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float64List, length, this)
  }
  setF(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  getErr(): number {
    return __S.getFloat64(16, this)
  }
  setErr(value: number): void {
    __S.setFloat64(16, value, this)
  }
  getInliers(): number {
    return __S.getInt32(24, this)
  }
  setInliers(value: number): void {
    __S.setInt32(24, value, this)
  }
  adoptMatches(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownMatches(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getMatches())
  }
  getMatches(): capnp.List<number> {
    return __S.getList(1, capnp.Int16List, this)
  }
  hasMatches(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initMatches(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Int16List, length, this)
  }
  setMatches(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  toString(): string {
    return 'OrbOdometry_' + super.toString()
  }
}
export class OrbFeatures extends __S {
  static readonly _capnp = { displayName: 'OrbFeatures', id: 'cd60164a8a0159ef', size: new __O(16, 5) }
  getTimestampEof(): capnp.Uint64 {
    return __S.getUint64(0, this)
  }
  setTimestampEof(value: capnp.Uint64): void {
    __S.setUint64(0, value, this)
  }
  adoptXs(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownXs(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getXs())
  }
  getXs(): capnp.List<number> {
    return __S.getList(0, capnp.Float32List, this)
  }
  hasXs(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initXs(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float32List, length, this)
  }
  setXs(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptYs(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownYs(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getYs())
  }
  getYs(): capnp.List<number> {
    return __S.getList(1, capnp.Float32List, this)
  }
  hasYs(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initYs(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Float32List, length, this)
  }
  setYs(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  adoptDescriptors(value: capnp.Orphan<capnp.Data>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownDescriptors(): capnp.Orphan<capnp.Data> {
    return __S.disown(this.getDescriptors())
  }
  getDescriptors(): capnp.Data {
    return __S.getData(2, this)
  }
  hasDescriptors(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initDescriptors(length: number): capnp.Data {
    return __S.initData(2, length, this)
  }
  setDescriptors(value: capnp.Data): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  adoptOctaves(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(3, this))
  }
  disownOctaves(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getOctaves())
  }
  getOctaves(): capnp.List<number> {
    return __S.getList(3, capnp.Int8List, this)
  }
  hasOctaves(): boolean {
    return !__S.isNull(__S.getPointer(3, this))
  }
  initOctaves(length: number): capnp.List<number> {
    return __S.initList(3, capnp.Int8List, length, this)
  }
  setOctaves(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(3, this))
  }
  getTimestampLastEof(): capnp.Uint64 {
    return __S.getUint64(8, this)
  }
  setTimestampLastEof(value: capnp.Uint64): void {
    __S.setUint64(8, value, this)
  }
  adoptMatches(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(4, this))
  }
  disownMatches(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getMatches())
  }
  getMatches(): capnp.List<number> {
    return __S.getList(4, capnp.Int16List, this)
  }
  hasMatches(): boolean {
    return !__S.isNull(__S.getPointer(4, this))
  }
  initMatches(length: number): capnp.List<number> {
    return __S.initList(4, capnp.Int16List, length, this)
  }
  setMatches(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(4, this))
  }
  toString(): string {
    return 'OrbFeatures_' + super.toString()
  }
}
export class OrbFeaturesSummary extends __S {
  static readonly _capnp = { displayName: 'OrbFeaturesSummary', id: 'd500d30c5803fa4f', size: new __O(32, 0) }
  getTimestampEof(): capnp.Uint64 {
    return __S.getUint64(0, this)
  }
  setTimestampEof(value: capnp.Uint64): void {
    __S.setUint64(0, value, this)
  }
  getTimestampLastEof(): capnp.Uint64 {
    return __S.getUint64(8, this)
  }
  setTimestampLastEof(value: capnp.Uint64): void {
    __S.setUint64(8, value, this)
  }
  getFeatureCount(): number {
    return __S.getUint16(16, this)
  }
  setFeatureCount(value: number): void {
    __S.setUint16(16, value, this)
  }
  getMatchCount(): number {
    return __S.getUint16(18, this)
  }
  setMatchCount(value: number): void {
    __S.setUint16(18, value, this)
  }
  getComputeNs(): capnp.Uint64 {
    return __S.getUint64(24, this)
  }
  setComputeNs(value: capnp.Uint64): void {
    __S.setUint64(24, value, this)
  }
  toString(): string {
    return 'OrbFeaturesSummary_' + super.toString()
  }
}
export class OrbKeyFrame extends __S {
  static readonly _capnp = { displayName: 'OrbKeyFrame', id: 'c8233c0345e27e24', size: new __O(8, 3) }
  static _Dpos: capnp.ListCtor<ECEFPoint>
  getId(): capnp.Uint64 {
    return __S.getUint64(0, this)
  }
  setId(value: capnp.Uint64): void {
    __S.setUint64(0, value, this)
  }
  adoptPos(value: capnp.Orphan<ECEFPoint>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownPos(): capnp.Orphan<ECEFPoint> {
    return __S.disown(this.getPos())
  }
  getPos(): ECEFPoint {
    return __S.getStruct(0, ECEFPoint, this)
  }
  hasPos(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initPos(): ECEFPoint {
    return __S.initStructAt(0, ECEFPoint, this)
  }
  setPos(value: ECEFPoint): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptDpos(value: capnp.Orphan<capnp.List<ECEFPoint>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownDpos(): capnp.Orphan<capnp.List<ECEFPoint>> {
    return __S.disown(this.getDpos())
  }
  getDpos(): capnp.List<ECEFPoint> {
    return __S.getList(1, OrbKeyFrame._Dpos, this)
  }
  hasDpos(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initDpos(length: number): capnp.List<ECEFPoint> {
    return __S.initList(1, OrbKeyFrame._Dpos, length, this)
  }
  setDpos(value: capnp.List<ECEFPoint>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  adoptDescriptors(value: capnp.Orphan<capnp.Data>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownDescriptors(): capnp.Orphan<capnp.Data> {
    return __S.disown(this.getDescriptors())
  }
  getDescriptors(): capnp.Data {
    return __S.getData(2, this)
  }
  hasDescriptors(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initDescriptors(length: number): capnp.Data {
    return __S.initData(2, length, this)
  }
  setDescriptors(value: capnp.Data): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  toString(): string {
    return 'OrbKeyFrame_' + super.toString()
  }
}
export class KalmanOdometry extends __S {
  static readonly _capnp = { displayName: 'KalmanOdometry', id: '92e21bb7ea38793a', size: new __O(0, 4) }
  adoptTrans(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownTrans(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getTrans())
  }
  getTrans(): capnp.List<number> {
    return __S.getList(0, capnp.Float32List, this)
  }
  hasTrans(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initTrans(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float32List, length, this)
  }
  setTrans(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptRot(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownRot(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getRot())
  }
  getRot(): capnp.List<number> {
    return __S.getList(1, capnp.Float32List, this)
  }
  hasRot(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initRot(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Float32List, length, this)
  }
  setRot(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  adoptTransStd(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownTransStd(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getTransStd())
  }
  getTransStd(): capnp.List<number> {
    return __S.getList(2, capnp.Float32List, this)
  }
  hasTransStd(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initTransStd(length: number): capnp.List<number> {
    return __S.initList(2, capnp.Float32List, length, this)
  }
  setTransStd(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  adoptRotStd(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(3, this))
  }
  disownRotStd(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getRotStd())
  }
  getRotStd(): capnp.List<number> {
    return __S.getList(3, capnp.Float32List, this)
  }
  hasRotStd(): boolean {
    return !__S.isNull(__S.getPointer(3, this))
  }
  initRotStd(length: number): capnp.List<number> {
    return __S.initList(3, capnp.Float32List, length, this)
  }
  setRotStd(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(3, this))
  }
  toString(): string {
    return 'KalmanOdometry_' + super.toString()
  }
}
export class OrbObservation extends __S {
  static readonly _capnp = { displayName: 'OrbObservation', id: '9b326d4e436afec7', size: new __O(16, 2) }
  getObservationMonoTime(): capnp.Uint64 {
    return __S.getUint64(0, this)
  }
  setObservationMonoTime(value: capnp.Uint64): void {
    __S.setUint64(0, value, this)
  }
  adoptNormalizedCoordinates(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownNormalizedCoordinates(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getNormalizedCoordinates())
  }
  getNormalizedCoordinates(): capnp.List<number> {
    return __S.getList(0, capnp.Float32List, this)
  }
  hasNormalizedCoordinates(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initNormalizedCoordinates(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float32List, length, this)
  }
  setNormalizedCoordinates(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptLocationECEF(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownLocationECEF(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getLocationECEF())
  }
  getLocationECEF(): capnp.List<number> {
    return __S.getList(1, capnp.Float64List, this)
  }
  hasLocationECEF(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initLocationECEF(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Float64List, length, this)
  }
  setLocationECEF(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  getMatchDistance(): number {
    return __S.getUint32(8, this)
  }
  setMatchDistance(value: number): void {
    __S.setUint32(8, value, this)
  }
  toString(): string {
    return 'OrbObservation_' + super.toString()
  }
}
export class CalibrationFeatures extends __S {
  static readonly _capnp = { displayName: 'CalibrationFeatures', id: '8fdfadb254ea867a', size: new __O(8, 3) }
  getFrameId(): number {
    return __S.getUint32(0, this)
  }
  setFrameId(value: number): void {
    __S.setUint32(0, value, this)
  }
  adoptP0(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownP0(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getP0())
  }
  getP0(): capnp.List<number> {
    return __S.getList(0, capnp.Float32List, this)
  }
  hasP0(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initP0(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Float32List, length, this)
  }
  setP0(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptP1(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownP1(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getP1())
  }
  getP1(): capnp.List<number> {
    return __S.getList(1, capnp.Float32List, this)
  }
  hasP1(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initP1(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Float32List, length, this)
  }
  setP1(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  adoptStatus(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownStatus(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getStatus())
  }
  getStatus(): capnp.List<number> {
    return __S.getList(2, capnp.Int8List, this)
  }
  hasStatus(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initStatus(length: number): capnp.List<number> {
    return __S.initList(2, capnp.Int8List, length, this)
  }
  setStatus(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  toString(): string {
    return 'CalibrationFeatures_' + super.toString()
  }
}
export class NavStatus_Address extends __S {
  static readonly _capnp = { displayName: 'Address', id: 'ce7cd672cacc7814', size: new __O(16, 7) }
  getTitle(): string {
    return __S.getText(0, this)
  }
  setTitle(value: string): void {
    __S.setText(0, value, this)
  }
  getLat(): number {
    return __S.getFloat64(0, this)
  }
  setLat(value: number): void {
    __S.setFloat64(0, value, this)
  }
  getLng(): number {
    return __S.getFloat64(8, this)
  }
  setLng(value: number): void {
    __S.setFloat64(8, value, this)
  }
  getHouse(): string {
    return __S.getText(1, this)
  }
  setHouse(value: string): void {
    __S.setText(1, value, this)
  }
  getAddress(): string {
    return __S.getText(2, this)
  }
  setAddress(value: string): void {
    __S.setText(2, value, this)
  }
  getStreet(): string {
    return __S.getText(3, this)
  }
  setStreet(value: string): void {
    __S.setText(3, value, this)
  }
  getCity(): string {
    return __S.getText(4, this)
  }
  setCity(value: string): void {
    __S.setText(4, value, this)
  }
  getState(): string {
    return __S.getText(5, this)
  }
  setState(value: string): void {
    __S.setText(5, value, this)
  }
  getCountry(): string {
    return __S.getText(6, this)
  }
  setCountry(value: string): void {
    __S.setText(6, value, this)
  }
  toString(): string {
    return 'NavStatus_Address_' + super.toString()
  }
}
export class NavStatus extends __S {
  static readonly Address = NavStatus_Address
  static readonly _capnp = { displayName: 'NavStatus', id: 'bd8822120928120c', size: new __O(8, 1) }
  getIsNavigating(): boolean {
    return __S.getBit(0, this)
  }
  setIsNavigating(value: boolean): void {
    __S.setBit(0, value, this)
  }
  adoptCurrentAddress(value: capnp.Orphan<NavStatus_Address>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownCurrentAddress(): capnp.Orphan<NavStatus_Address> {
    return __S.disown(this.getCurrentAddress())
  }
  getCurrentAddress(): NavStatus_Address {
    return __S.getStruct(0, NavStatus_Address, this)
  }
  hasCurrentAddress(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initCurrentAddress(): NavStatus_Address {
    return __S.initStructAt(0, NavStatus_Address, this)
  }
  setCurrentAddress(value: NavStatus_Address): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  toString(): string {
    return 'NavStatus_' + super.toString()
  }
}
export class NavUpdate_LatLng extends __S {
  static readonly _capnp = { displayName: 'LatLng', id: '9eaef9187cadbb9b', size: new __O(16, 0) }
  getLat(): number {
    return __S.getFloat64(0, this)
  }
  setLat(value: number): void {
    __S.setFloat64(0, value, this)
  }
  getLng(): number {
    return __S.getFloat64(8, this)
  }
  setLng(value: number): void {
    __S.setFloat64(8, value, this)
  }
  toString(): string {
    return 'NavUpdate_LatLng_' + super.toString()
  }
}
export enum NavUpdate_Segment_Instruction {
  TURN_LEFT,
  TURN_RIGHT,
  KEEP_LEFT,
  KEEP_RIGHT,
  STRAIGHT,
  ROUNDABOUT_EXIT_NUMBER,
  ROUNDABOUT_EXIT,
  ROUNDABOUT_TURN_LEFT,
  UNKN8,
  ROUNDABOUT_STRAIGHT,
  UNKN10,
  ROUNDABOUT_TURN_RIGHT,
  UNKN12,
  ROUNDABOUT_UTURN,
  UNKN14,
  ARRIVE,
  EXIT_LEFT,
  EXIT_RIGHT,
  UNKN18,
  UTURN,
}
export class NavUpdate_Segment extends __S {
  static readonly Instruction = NavUpdate_Segment_Instruction
  static readonly _capnp = { displayName: 'Segment', id: 'a5b39b4fc4d7da3f', size: new __O(24, 3) }
  static _Parts: capnp.ListCtor<NavUpdate_LatLng>
  adoptFrom(value: capnp.Orphan<NavUpdate_LatLng>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownFrom(): capnp.Orphan<NavUpdate_LatLng> {
    return __S.disown(this.getFrom())
  }
  getFrom(): NavUpdate_LatLng {
    return __S.getStruct(0, NavUpdate_LatLng, this)
  }
  hasFrom(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initFrom(): NavUpdate_LatLng {
    return __S.initStructAt(0, NavUpdate_LatLng, this)
  }
  setFrom(value: NavUpdate_LatLng): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptTo(value: capnp.Orphan<NavUpdate_LatLng>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownTo(): capnp.Orphan<NavUpdate_LatLng> {
    return __S.disown(this.getTo())
  }
  getTo(): NavUpdate_LatLng {
    return __S.getStruct(1, NavUpdate_LatLng, this)
  }
  hasTo(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initTo(): NavUpdate_LatLng {
    return __S.initStructAt(1, NavUpdate_LatLng, this)
  }
  setTo(value: NavUpdate_LatLng): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  getUpdateTime(): number {
    return __S.getInt32(0, this)
  }
  setUpdateTime(value: number): void {
    __S.setInt32(0, value, this)
  }
  getDistance(): number {
    return __S.getInt32(4, this)
  }
  setDistance(value: number): void {
    __S.setInt32(4, value, this)
  }
  getCrossTime(): number {
    return __S.getInt32(8, this)
  }
  setCrossTime(value: number): void {
    __S.setInt32(8, value, this)
  }
  getExitNo(): number {
    return __S.getInt32(12, this)
  }
  setExitNo(value: number): void {
    __S.setInt32(12, value, this)
  }
  getInstruction(): NavUpdate_Segment_Instruction {
    return __S.getUint16(16, this)
  }
  setInstruction(value: NavUpdate_Segment_Instruction): void {
    __S.setUint16(16, value, this)
  }
  adoptParts(value: capnp.Orphan<capnp.List<NavUpdate_LatLng>>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownParts(): capnp.Orphan<capnp.List<NavUpdate_LatLng>> {
    return __S.disown(this.getParts())
  }
  getParts(): capnp.List<NavUpdate_LatLng> {
    return __S.getList(2, NavUpdate_Segment._Parts, this)
  }
  hasParts(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initParts(length: number): capnp.List<NavUpdate_LatLng> {
    return __S.initList(2, NavUpdate_Segment._Parts, length, this)
  }
  setParts(value: capnp.List<NavUpdate_LatLng>): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  toString(): string {
    return 'NavUpdate_Segment_' + super.toString()
  }
}
export class NavUpdate extends __S {
  static readonly LatLng = NavUpdate_LatLng
  static readonly Segment = NavUpdate_Segment
  static readonly _capnp = { displayName: 'NavUpdate', id: 'db98be6565516acb', size: new __O(8, 1) }
  static _Segments: capnp.ListCtor<NavUpdate_Segment>
  getIsNavigating(): boolean {
    return __S.getBit(0, this)
  }
  setIsNavigating(value: boolean): void {
    __S.setBit(0, value, this)
  }
  getCurSegment(): number {
    return __S.getInt32(4, this)
  }
  setCurSegment(value: number): void {
    __S.setInt32(4, value, this)
  }
  adoptSegments(value: capnp.Orphan<capnp.List<NavUpdate_Segment>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownSegments(): capnp.Orphan<capnp.List<NavUpdate_Segment>> {
    return __S.disown(this.getSegments())
  }
  getSegments(): capnp.List<NavUpdate_Segment> {
    return __S.getList(0, NavUpdate._Segments, this)
  }
  hasSegments(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initSegments(length: number): capnp.List<NavUpdate_Segment> {
    return __S.initList(0, NavUpdate._Segments, length, this)
  }
  setSegments(value: capnp.List<NavUpdate_Segment>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  toString(): string {
    return 'NavUpdate_' + super.toString()
  }
}
export enum TrafficEvent_Type {
  STOP_SIGN,
  LIGHT_RED,
  LIGHT_YELLOW,
  LIGHT_GREEN,
  STOP_LIGHT,
}
export enum TrafficEvent_Action {
  NONE,
  YIELD,
  STOP,
  RESUME_READY,
}
export class TrafficEvent extends __S {
  static readonly Type = TrafficEvent_Type
  static readonly Action = TrafficEvent_Action
  static readonly _capnp = { displayName: 'TrafficEvent', id: 'acfa74a094e62626', size: new __O(16, 0) }
  getType(): TrafficEvent_Type {
    return __S.getUint16(0, this)
  }
  setType(value: TrafficEvent_Type): void {
    __S.setUint16(0, value, this)
  }
  getDistance(): number {
    return __S.getFloat32(4, this)
  }
  setDistance(value: number): void {
    __S.setFloat32(4, value, this)
  }
  getAction(): TrafficEvent_Action {
    return __S.getUint16(2, this)
  }
  setAction(value: TrafficEvent_Action): void {
    __S.setUint16(2, value, this)
  }
  getResuming(): boolean {
    return __S.getBit(64, this)
  }
  setResuming(value: boolean): void {
    __S.setBit(64, value, this)
  }
  toString(): string {
    return 'TrafficEvent_' + super.toString()
  }
}
export class AndroidGnss_Measurements_Clock extends __S {
  static readonly _capnp = { displayName: 'Clock', id: 'a0e27b453a38f450', size: new __O(72, 0) }
  getTimeNanos(): capnp.Int64 {
    return __S.getInt64(0, this)
  }
  setTimeNanos(value: capnp.Int64): void {
    __S.setInt64(0, value, this)
  }
  getHardwareClockDiscontinuityCount(): number {
    return __S.getInt32(8, this)
  }
  setHardwareClockDiscontinuityCount(value: number): void {
    __S.setInt32(8, value, this)
  }
  getHasTimeUncertaintyNanos(): boolean {
    return __S.getBit(96, this)
  }
  setHasTimeUncertaintyNanos(value: boolean): void {
    __S.setBit(96, value, this)
  }
  getTimeUncertaintyNanos(): number {
    return __S.getFloat64(16, this)
  }
  setTimeUncertaintyNanos(value: number): void {
    __S.setFloat64(16, value, this)
  }
  getHasLeapSecond(): boolean {
    return __S.getBit(97, this)
  }
  setHasLeapSecond(value: boolean): void {
    __S.setBit(97, value, this)
  }
  getLeapSecond(): number {
    return __S.getInt32(24, this)
  }
  setLeapSecond(value: number): void {
    __S.setInt32(24, value, this)
  }
  getHasFullBiasNanos(): boolean {
    return __S.getBit(98, this)
  }
  setHasFullBiasNanos(value: boolean): void {
    __S.setBit(98, value, this)
  }
  getFullBiasNanos(): capnp.Int64 {
    return __S.getInt64(32, this)
  }
  setFullBiasNanos(value: capnp.Int64): void {
    __S.setInt64(32, value, this)
  }
  getHasBiasNanos(): boolean {
    return __S.getBit(99, this)
  }
  setHasBiasNanos(value: boolean): void {
    __S.setBit(99, value, this)
  }
  getBiasNanos(): number {
    return __S.getFloat64(40, this)
  }
  setBiasNanos(value: number): void {
    __S.setFloat64(40, value, this)
  }
  getHasBiasUncertaintyNanos(): boolean {
    return __S.getBit(100, this)
  }
  setHasBiasUncertaintyNanos(value: boolean): void {
    __S.setBit(100, value, this)
  }
  getBiasUncertaintyNanos(): number {
    return __S.getFloat64(48, this)
  }
  setBiasUncertaintyNanos(value: number): void {
    __S.setFloat64(48, value, this)
  }
  getHasDriftNanosPerSecond(): boolean {
    return __S.getBit(101, this)
  }
  setHasDriftNanosPerSecond(value: boolean): void {
    __S.setBit(101, value, this)
  }
  getDriftNanosPerSecond(): number {
    return __S.getFloat64(56, this)
  }
  setDriftNanosPerSecond(value: number): void {
    __S.setFloat64(56, value, this)
  }
  getHasDriftUncertaintyNanosPerSecond(): boolean {
    return __S.getBit(102, this)
  }
  setHasDriftUncertaintyNanosPerSecond(value: boolean): void {
    __S.setBit(102, value, this)
  }
  getDriftUncertaintyNanosPerSecond(): number {
    return __S.getFloat64(64, this)
  }
  setDriftUncertaintyNanosPerSecond(value: number): void {
    __S.setFloat64(64, value, this)
  }
  toString(): string {
    return 'AndroidGnss_Measurements_Clock_' + super.toString()
  }
}
export enum AndroidGnss_Measurements_Measurement_Constellation {
  UNKNOWN,
  GPS,
  SBAS,
  GLONASS,
  QZSS,
  BEIDOU,
  GALILEO,
}
export enum AndroidGnss_Measurements_Measurement_State {
  UNKNOWN,
  CODE_LOCK,
  BIT_SYNC,
  SUBFRAME_SYNC,
  TOW_DECODED,
  MSEC_AMBIGUOUS,
  SYMBOL_SYNC,
  GLO_STRING_SYNC,
  GLO_TOD_DECODED,
  BDS_D2BIT_SYNC,
  BDS_D2SUBFRAME_SYNC,
  GAL_E1BC_CODE_LOCK,
  GAL_E1C2ND_CODE_LOCK,
  GAL_E1B_PAGE_SYNC,
  SBAS_SYNC,
}
export enum AndroidGnss_Measurements_Measurement_MultipathIndicator {
  UNKNOWN,
  DETECTED,
  NOT_DETECTED,
}
export class AndroidGnss_Measurements_Measurement extends __S {
  static readonly Constellation = AndroidGnss_Measurements_Measurement_Constellation
  static readonly State = AndroidGnss_Measurements_Measurement_State
  static readonly MultipathIndicator = AndroidGnss_Measurements_Measurement_MultipathIndicator
  static readonly _capnp = { displayName: 'Measurement', id: 'd949bf717d77614d', size: new __O(120, 0) }
  getSvId(): number {
    return __S.getInt32(0, this)
  }
  setSvId(value: number): void {
    __S.setInt32(0, value, this)
  }
  getConstellation(): AndroidGnss_Measurements_Measurement_Constellation {
    return __S.getUint16(4, this)
  }
  setConstellation(value: AndroidGnss_Measurements_Measurement_Constellation): void {
    __S.setUint16(4, value, this)
  }
  getTimeOffsetNanos(): number {
    return __S.getFloat64(8, this)
  }
  setTimeOffsetNanos(value: number): void {
    __S.setFloat64(8, value, this)
  }
  getState(): number {
    return __S.getInt32(16, this)
  }
  setState(value: number): void {
    __S.setInt32(16, value, this)
  }
  getReceivedSvTimeNanos(): capnp.Int64 {
    return __S.getInt64(24, this)
  }
  setReceivedSvTimeNanos(value: capnp.Int64): void {
    __S.setInt64(24, value, this)
  }
  getReceivedSvTimeUncertaintyNanos(): capnp.Int64 {
    return __S.getInt64(32, this)
  }
  setReceivedSvTimeUncertaintyNanos(value: capnp.Int64): void {
    __S.setInt64(32, value, this)
  }
  getCn0DbHz(): number {
    return __S.getFloat64(40, this)
  }
  setCn0DbHz(value: number): void {
    __S.setFloat64(40, value, this)
  }
  getPseudorangeRateMetersPerSecond(): number {
    return __S.getFloat64(48, this)
  }
  setPseudorangeRateMetersPerSecond(value: number): void {
    __S.setFloat64(48, value, this)
  }
  getPseudorangeRateUncertaintyMetersPerSecond(): number {
    return __S.getFloat64(56, this)
  }
  setPseudorangeRateUncertaintyMetersPerSecond(value: number): void {
    __S.setFloat64(56, value, this)
  }
  getAccumulatedDeltaRangeState(): number {
    return __S.getInt32(20, this)
  }
  setAccumulatedDeltaRangeState(value: number): void {
    __S.setInt32(20, value, this)
  }
  getAccumulatedDeltaRangeMeters(): number {
    return __S.getFloat64(64, this)
  }
  setAccumulatedDeltaRangeMeters(value: number): void {
    __S.setFloat64(64, value, this)
  }
  getAccumulatedDeltaRangeUncertaintyMeters(): number {
    return __S.getFloat64(72, this)
  }
  setAccumulatedDeltaRangeUncertaintyMeters(value: number): void {
    __S.setFloat64(72, value, this)
  }
  getHasCarrierFrequencyHz(): boolean {
    return __S.getBit(48, this)
  }
  setHasCarrierFrequencyHz(value: boolean): void {
    __S.setBit(48, value, this)
  }
  getCarrierFrequencyHz(): number {
    return __S.getFloat32(80, this)
  }
  setCarrierFrequencyHz(value: number): void {
    __S.setFloat32(80, value, this)
  }
  getHasCarrierCycles(): boolean {
    return __S.getBit(49, this)
  }
  setHasCarrierCycles(value: boolean): void {
    __S.setBit(49, value, this)
  }
  getCarrierCycles(): capnp.Int64 {
    return __S.getInt64(88, this)
  }
  setCarrierCycles(value: capnp.Int64): void {
    __S.setInt64(88, value, this)
  }
  getHasCarrierPhase(): boolean {
    return __S.getBit(50, this)
  }
  setHasCarrierPhase(value: boolean): void {
    __S.setBit(50, value, this)
  }
  getCarrierPhase(): number {
    return __S.getFloat64(96, this)
  }
  setCarrierPhase(value: number): void {
    __S.setFloat64(96, value, this)
  }
  getHasCarrierPhaseUncertainty(): boolean {
    return __S.getBit(51, this)
  }
  setHasCarrierPhaseUncertainty(value: boolean): void {
    __S.setBit(51, value, this)
  }
  getCarrierPhaseUncertainty(): number {
    return __S.getFloat64(104, this)
  }
  setCarrierPhaseUncertainty(value: number): void {
    __S.setFloat64(104, value, this)
  }
  getHasSnrInDb(): boolean {
    return __S.getBit(52, this)
  }
  setHasSnrInDb(value: boolean): void {
    __S.setBit(52, value, this)
  }
  getSnrInDb(): number {
    return __S.getFloat64(112, this)
  }
  setSnrInDb(value: number): void {
    __S.setFloat64(112, value, this)
  }
  getMultipathIndicator(): AndroidGnss_Measurements_Measurement_MultipathIndicator {
    return __S.getUint16(84, this)
  }
  setMultipathIndicator(value: AndroidGnss_Measurements_Measurement_MultipathIndicator): void {
    __S.setUint16(84, value, this)
  }
  toString(): string {
    return 'AndroidGnss_Measurements_Measurement_' + super.toString()
  }
}
export class AndroidGnss_Measurements extends __S {
  static readonly Clock = AndroidGnss_Measurements_Clock
  static readonly Measurement = AndroidGnss_Measurements_Measurement
  static readonly _capnp = { displayName: 'Measurements', id: 'a20710d4f428d6cd', size: new __O(0, 2) }
  static _Measurements: capnp.ListCtor<AndroidGnss_Measurements_Measurement>
  adoptClock(value: capnp.Orphan<AndroidGnss_Measurements_Clock>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownClock(): capnp.Orphan<AndroidGnss_Measurements_Clock> {
    return __S.disown(this.getClock())
  }
  getClock(): AndroidGnss_Measurements_Clock {
    return __S.getStruct(0, AndroidGnss_Measurements_Clock, this)
  }
  hasClock(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initClock(): AndroidGnss_Measurements_Clock {
    return __S.initStructAt(0, AndroidGnss_Measurements_Clock, this)
  }
  setClock(value: AndroidGnss_Measurements_Clock): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptMeasurements(value: capnp.Orphan<capnp.List<AndroidGnss_Measurements_Measurement>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownMeasurements(): capnp.Orphan<capnp.List<AndroidGnss_Measurements_Measurement>> {
    return __S.disown(this.getMeasurements())
  }
  getMeasurements(): capnp.List<AndroidGnss_Measurements_Measurement> {
    return __S.getList(1, AndroidGnss_Measurements._Measurements, this)
  }
  hasMeasurements(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initMeasurements(length: number): capnp.List<AndroidGnss_Measurements_Measurement> {
    return __S.initList(1, AndroidGnss_Measurements._Measurements, length, this)
  }
  setMeasurements(value: capnp.List<AndroidGnss_Measurements_Measurement>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  toString(): string {
    return 'AndroidGnss_Measurements_' + super.toString()
  }
}
export enum AndroidGnss_NavigationMessage_Status {
  UNKNOWN,
  PARITY_PASSED,
  PARITY_REBUILT,
}
export class AndroidGnss_NavigationMessage extends __S {
  static readonly Status = AndroidGnss_NavigationMessage_Status
  static readonly _capnp = { displayName: 'NavigationMessage', id: 'e2517b083095fd4e', size: new __O(24, 1) }
  getType(): number {
    return __S.getInt32(0, this)
  }
  setType(value: number): void {
    __S.setInt32(0, value, this)
  }
  getSvId(): number {
    return __S.getInt32(4, this)
  }
  setSvId(value: number): void {
    __S.setInt32(4, value, this)
  }
  getMessageId(): number {
    return __S.getInt32(8, this)
  }
  setMessageId(value: number): void {
    __S.setInt32(8, value, this)
  }
  getSubmessageId(): number {
    return __S.getInt32(12, this)
  }
  setSubmessageId(value: number): void {
    __S.setInt32(12, value, this)
  }
  adoptData(value: capnp.Orphan<capnp.Data>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownData(): capnp.Orphan<capnp.Data> {
    return __S.disown(this.getData())
  }
  getData(): capnp.Data {
    return __S.getData(0, this)
  }
  hasData(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initData(length: number): capnp.Data {
    return __S.initData(0, length, this)
  }
  setData(value: capnp.Data): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  getStatus(): AndroidGnss_NavigationMessage_Status {
    return __S.getUint16(16, this)
  }
  setStatus(value: AndroidGnss_NavigationMessage_Status): void {
    __S.setUint16(16, value, this)
  }
  toString(): string {
    return 'AndroidGnss_NavigationMessage_' + super.toString()
  }
}
export enum AndroidGnss_Which {
  MEASUREMENTS = 0,
  NAVIGATION_MESSAGE = 1,
}
export class AndroidGnss extends __S {
  static readonly MEASUREMENTS = AndroidGnss_Which.MEASUREMENTS
  static readonly NAVIGATION_MESSAGE = AndroidGnss_Which.NAVIGATION_MESSAGE
  static readonly Measurements = AndroidGnss_Measurements
  static readonly NavigationMessage = AndroidGnss_NavigationMessage
  static readonly _capnp = { displayName: 'AndroidGnss', id: 'dfdf30d03fc485bd', size: new __O(8, 1) }
  adoptMeasurements(value: capnp.Orphan<AndroidGnss_Measurements>): void {
    __S.setUint16(0, 0, this)
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownMeasurements(): capnp.Orphan<AndroidGnss_Measurements> {
    return __S.disown(this.getMeasurements())
  }
  getMeasurements(): AndroidGnss_Measurements {
    __S.testWhich('measurements', __S.getUint16(0, this), 0, this)
    return __S.getStruct(0, AndroidGnss_Measurements, this)
  }
  hasMeasurements(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initMeasurements(): AndroidGnss_Measurements {
    __S.setUint16(0, 0, this)
    return __S.initStructAt(0, AndroidGnss_Measurements, this)
  }
  isMeasurements(): boolean {
    return __S.getUint16(0, this) === 0
  }
  setMeasurements(value: AndroidGnss_Measurements): void {
    __S.setUint16(0, 0, this)
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptNavigationMessage(value: capnp.Orphan<AndroidGnss_NavigationMessage>): void {
    __S.setUint16(0, 1, this)
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownNavigationMessage(): capnp.Orphan<AndroidGnss_NavigationMessage> {
    return __S.disown(this.getNavigationMessage())
  }
  getNavigationMessage(): AndroidGnss_NavigationMessage {
    __S.testWhich('navigationMessage', __S.getUint16(0, this), 1, this)
    return __S.getStruct(0, AndroidGnss_NavigationMessage, this)
  }
  hasNavigationMessage(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initNavigationMessage(): AndroidGnss_NavigationMessage {
    __S.setUint16(0, 1, this)
    return __S.initStructAt(0, AndroidGnss_NavigationMessage, this)
  }
  isNavigationMessage(): boolean {
    return __S.getUint16(0, this) === 1
  }
  setNavigationMessage(value: AndroidGnss_NavigationMessage): void {
    __S.setUint16(0, 1, this)
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  toString(): string {
    return 'AndroidGnss_' + super.toString()
  }
  which(): AndroidGnss_Which {
    return __S.getUint16(0, this)
  }
}
export class LidarPts extends __S {
  static readonly _capnp = { displayName: 'LidarPts', id: 'e3d6685d4e9d8f7a', size: new __O(8, 4) }
  adoptR(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(0, this))
  }
  disownR(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getR())
  }
  getR(): capnp.List<number> {
    return __S.getList(0, capnp.Uint16List, this)
  }
  hasR(): boolean {
    return !__S.isNull(__S.getPointer(0, this))
  }
  initR(length: number): capnp.List<number> {
    return __S.initList(0, capnp.Uint16List, length, this)
  }
  setR(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(0, this))
  }
  adoptTheta(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(1, this))
  }
  disownTheta(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getTheta())
  }
  getTheta(): capnp.List<number> {
    return __S.getList(1, capnp.Uint16List, this)
  }
  hasTheta(): boolean {
    return !__S.isNull(__S.getPointer(1, this))
  }
  initTheta(length: number): capnp.List<number> {
    return __S.initList(1, capnp.Uint16List, length, this)
  }
  setTheta(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(1, this))
  }
  adoptReflect(value: capnp.Orphan<capnp.List<number>>): void {
    __S.adopt(value, __S.getPointer(2, this))
  }
  disownReflect(): capnp.Orphan<capnp.List<number>> {
    return __S.disown(this.getReflect())
  }
  getReflect(): capnp.List<number> {
    return __S.getList(2, capnp.Uint8List, this)
  }
  hasReflect(): boolean {
    return !__S.isNull(__S.getPointer(2, this))
  }
  initReflect(length: number): capnp.List<number> {
    return __S.initList(2, capnp.Uint8List, length, this)
  }
  setReflect(value: capnp.List<number>): void {
    __S.copyFrom(value, __S.getPointer(2, this))
  }
  getIdx(): capnp.Uint64 {
    return __S.getUint64(0, this)
  }
  setIdx(value: capnp.Uint64): void {
    __S.setUint64(0, value, this)
  }
  adoptPkt(value: capnp.Orphan<capnp.Data>): void {
    __S.adopt(value, __S.getPointer(3, this))
  }
  disownPkt(): capnp.Orphan<capnp.Data> {
    return __S.disown(this.getPkt())
  }
  getPkt(): capnp.Data {
    return __S.getData(3, this)
  }
  hasPkt(): boolean {
    return !__S.isNull(__S.getPointer(3, this))
  }
  initPkt(length: number): capnp.Data {
    return __S.initData(3, length, this)
  }
  setPkt(value: capnp.Data): void {
    __S.copyFrom(value, __S.getPointer(3, this))
  }
  toString(): string {
    return 'LidarPts_' + super.toString()
  }
}
GPSPlannerPoints._PointsDEPRECATED = capnp.CompositeList(ECEFPointDEPRECATED)
GPSPlannerPoints._Points = capnp.CompositeList(ECEFPoint)
GPSPlannerPlan._PointsDEPRECATED = capnp.CompositeList(ECEFPointDEPRECATED)
GPSPlannerPlan._Points = capnp.CompositeList(ECEFPoint)
OrbKeyFrame._Dpos = capnp.CompositeList(ECEFPoint)
NavUpdate_Segment._Parts = capnp.CompositeList(NavUpdate_LatLng)
NavUpdate._Segments = capnp.CompositeList(NavUpdate_Segment)
AndroidGnss_Measurements._Measurements = capnp.CompositeList(AndroidGnss_Measurements_Measurement)
